Performance.create!(dancer_name: "Billy Bell", partner: "Lauren Gottileb", song: "Footloose", season: 7, style: "Broadway", dancer_id: 29, partner_id:152 )
Performance.create!(dancer_name: "Comfort Fedoke", partner: "Jose Ruiz", song: "Beautiful Monster", season: 7, style: "Hip-Hop", dancer_id: 44, partner_id:134 )
Performance.create!(dancer_name: "Kathryn McCormick", partner: "AdéChiké Torbert ", song: " Addicted to Love", season: 7, style: "Jazz", dancer_id: 96, partner_id:3 )
Performance.create!(dancer_name: "Pasha Kovalev", partner: "Melinda Sullivan ", song: "L-O-V-E", season: 7, style: "Jive", dancer_id: 138, partner_id: 165)
Performance.create!(dancer_name: "Allison Holker", partner: "Alex Wong", song: "Hallelujah", season: 7, style: "Contemporary", dancer_id: 10, partner_id:5 )
Performance.create!(dancer_name: "Alexie Agdeppa", partner: "Twitch Boss", song: "Butterfly", season: 7, style: "Hip-Hop", dancer_id: 8, partner_id:206 )
Performance.create!(dancer_name: "Lauren Froderman", partner: "Ade Obayomi", song: "Oh Yeah", season: 7, style: "Pop-Jazz", dancer_id: 151, partner_id:2 )
Performance.create!(dancer_name: "Kent Boyd", partner: "Anya Garnis", song: "Lady Marmalade", season: 7, style: "Cha-cha=cha", dancer_id: 146, partner_id:13 )
Performance.create!(dancer_name: "Ashley Galvan", partner: "Neil Haskell", song: "For All We Know", season: 7, style: "Contemporary", dancer_id: 20, partner_id:178 )
Performance.create!( dancer_name: "Courtney Galiano", partner: "Robert Roldan", song: "Norweg", season: 7, style: "African Jazz", dancer_id: 45, partner_id: 194)
Performance.create!( dancer_name: "Pasha Kovalev", partner: "Christina Santana", song: "Ira Deorum/Sanctus", season: 7, style: "Paso Doble", dancer_id: 138, partner_id:nil )
Performance.create!( dancer_name: "Allison Holker", partner: "AdéChiké Torbert", song: "Listen to Your Heart", season: 7, style: "Contemporary", dancer_id: 10, partner_id:3 )
Performance.create!( dancer_name: "Lauren Gottlieb", partner: "Alex Wong", song: "Summertime", season: 7, style: "Broadway", dancer_id: 152, partner_id: 194 )
Performance.create!( dancer_name: "Anya Garnis", partner: "Robert Roldan", song: "Argentine Tango", season: 7, style: "Argentine Tango", dancer_id: 13, partner_id:194 )
Performance.create!( dancer_name: "Ade Obayomi", partner: "Melinda Sullivan", song: "Squander", season: 7, style: "Contemporary", dancer_id: 2, partner_id:165 )
Performance.create!( dancer_name: "Kathryn McCormick", partner: "Jose Ruiz", song: "Marjaani Marjaani Kasama", season: 7, style: "Bollywood", dancer_id: 96, partner_id:134 )
Performance.create!( dancer_name: "Lauren Froderman", partner: "Dominic Sandoval", song: "If I Were a Boy", season: 7, style: "Lyrical Hip-Hop", dancer_id: 151, partner_id: )
Performance.create!( dancer_name: "Kent Boyd", partner: "Courtney Gailiano", song: "Amy Amy Amy", season: 7, style: "Jazz", dancer_id: 146, partner_id:45 )
Performance.create!( dancer_name: "Lauren Gottlieb", partner: "AdéChiké Torbert ", song: "Hot-N-Fun", season: 7, style: "Hip-Hop", dancer_id: 152, partner_id:3 )
Performance.create!( dancer_name: "Kent Boyd", partner: "Courtney Gailiano", song: "Amy Amy Amy", season: 7, style: "Jazz", dancer_id: 146, partner_id:45 )
Performance.create!( dancer_name: "Lauren Gottlieb", partner: "AdéChiké Torbert ", song: "Hot-N-Fun", season: 7, style: "Hip-Hop", dancer_id: 152, partner_id:3 )
Performance.create!( dancer_name: "Ashley Galvan", partner: "Ade Obayomi", song: "Cosmic Love", season: 7, style: "Contemporary", dancer_id: 20, partner_id:2 )
Performance.create!( dancer_name: "Courtney Galiano", partner: "Robert Roldan", song: "XXXO", season: 7, style: "Jazz", dancer_id: 45, partner_id:194 )
Performance.create!( dancer_name: "Pasha Kovalev", partner: "Melinda Sullivan", song: "Magdelena, Mi Amor", season: 7, style: "Salsa", dancer_id: 138, partner_id:165 )
Performance.create!( dancer_name: "Lauren Froderman", partner: "Neil Haskell", song: "Let me Entertain You", season: 7, style: "Broadway", dancer_id: 151, partner_id:178 )
Performance.create!(dancer_name: "Billy Bell", partner: "Kathryn McCormick", song: "Jar of Hearts", season: 7, style: "Contemporary", dancer_id: 29, partner_id:143 )
Performance.create!( dancer_name: "Anya Garnis", partner: "Jose Ruiz", song: "Long Time", season: 7, style: "Samba", dancer_id: 13, partner_id: 134)
Performance.create!( dancer_name: "Kent Boyd", partner: "Allison Holker", song: "Heartburn", season: 7, style: "Jazz", dancer_id: 146, partner_id:10 )
Performance.create!( dancer_name: "Alex Wong", partner: "Twitch Boss", song: "Hip-Hop", season: 7, style: "Hip-Hop", dancer_id: 5, partner_id: 206 )
Performance.create!(dancer_name:"Lauren Froderman" ,partner:"Pasha Kovalev" , song: "Telephone", season:7, style:"Cha-cha-cha", dancer_id: 151, partner_id:138)

Performance.create!(dancer_name:"Lauren Gottileb" ,partner:"Jose Ruiz" , song: "Never Tear us Apart", season:7, style:"Contemporary", dancer_id:152, partner_id:134 )
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Comfort Fedoke" , song: "You're not my Girl", season:7, style:"Hip-hop", dancer_id:146, partner_id:44 )
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"AdéChiké Torbert  " , song: "Is You or is You Ain't my Baby", season:7, style:"Jazz", dancer_id:45, partner_id:3 )
Performance.create!(dancer_name:"Billy Bell" ,partner:"Katee Shean" , song: "Broadway", season:7, style:"Broadway", dancer_id: 29, partner_id:142)
Performance.create!(dancer_name:"Ashley Galvan" ,partner:"Dominic Sandoval" , song: "How Low", season:7, style:"Hip-hop", dancer_id: 20, partner_id:54 )
Performance.create!(dancer_name:"Kathyrn McCormick" ,partner:"Robert Roldan" , song: "Sinking Feeling", season:7, style:"Jazz", dancer_id:143, partner_id: 194 )
Performance.create!(dancer_name:"AdéChiké Torbert  " ,partner:"Maria" , song: "Mourya Re", season:7, style:"Bollywood", dancer_id:3, partner_id: nil)
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Lauren Froderman" , song: "Collide", season:7, style:"Contemporary", dancer_id: 146, partner_id:151 )
Performance.create!(dancer_name:"Ashely Galvan" ,partner:"Robert Roldan" , song: "Man with the Hex", season:7, style:"Quickstep", dancer_id:20, partner_id: 194)
Performance.create!(dancer_name:"Billy Bell" ,partner:"Jose Ruiz" , song: "The Hunt", season:7, style:"African Jazz", dancer_id: 29, partner_id:134)
Performance.create!(dancer_name:"Lauren Foderman" ,partner:"Mark Kanemura" , song: "Jungle", season:7, style:"Tahitan", dancer_id: 151, partner_id: 156)
Performance.create!(dancer_name:"Anya Garnis" ,partner:"AdéChiké Torbert " , song: "Oyelo Que Te Convience", season:7, style:"Salsa", dancer_id: 13, partner_id:3)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Jose Ruiz" , song: "Mister Cellophane", season:7, style:"Broadway", dancer_id: 45, partner_id:134 )
Performance.create!(dancer_name:"Allison Holker" ,partner:"Robert Roldan" , song: "Fix you", season:7, style:"Contemporary", dancer_id: 10, partner_id: 194)
Performance.create!(dancer_name:"Billy Bell" ,partner:"Anya Garnis" , song: "Paradise by the Dashboard Light", season:7, style:"Jive", dancer_id: 20, partner_id:13)
Performance.create!(dancer_name:"Kent Boyd " ,partner:" Neil Haskell" , song: "Shoeless Joe from Hannibal, MO", season:7, style:"Broadway", dancer_id:146, partner_id: )
Performance.create!(dancer_name:"Billy Bell" ,partner:"Lauren Froderman" , song: "Boogie Shoes", season:7, style:"Jazz", dancer_id: 20, partner_id:151 )
Performance.create!(dancer_name:"Jose Ruiz" ,partner:"Dominic Sandoval" , song: "Battle for the Beat", season:7, style:"B-Boying", dancer_id:134, partner_id: 134)
Performance.create!(dancer_name:"Kent Boyd" ,partner:"AdéChiké Torbert " , song: "You only Disappear", season:7, style:"Contemporary", dancer_id:146, partner_id: )
Performance.create!(dancer_name:"Robert Roldan" ,partner:"Kathyrn McCormick" , song: "Instant Replay", season:7, style:"Disco", dancer_id:194, partner_id:143 )
Performance.create!(dancer_name:"Twitch Boss" ,partner:"Lauren Froderman" , song: "My Chick Bad", season:7, style:"Hip-hop", dancer_id: 206, partner_id:151)
Performance.create!(dancer_name:"Allison Holker" ,partner:"Jose Ruiz" , song: "Eternal Sunshine of the Mind theme", season:7, style:"Contemporary", dancer_id:10, partner_id:134 )
Performance.create!(dancer_name:"Lauren Gottileb" ,partner:"Robert Roldan" , song: "Wasted Time", season:7, style:"Jazz", dancer_id: 152, partner_id: 194 )
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Kathryn McCormick" , song: "Tightrope", season:7, style:"Jazz", dancer_id:146, partner_id:143 )
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"AdéChiké Torbert  " , song: "Fallin", season:7, style:"Lyrical Hip-hop", dancer_id: 44, partner_id:3 )
Performance.create!(dancer_name:"Lauren Froderman" ,partner:"Robert Roldan" , song: "Drummer Boy", season:7, style:"Samba", dancer_id: 151, partner_id:194 )
Performance.create!(dancer_name:"Jose Ruiz" ,partner:"AdéChiké Torbert " , song: "The Arrival", season:7, style:"Paso Doble", dancer_id: 134, partner_id:3 )
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Twitch Boss" , song: "Pro Nails", season:7, style:"Stepping", dancer_id: 146, partner_id:206 )
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Anya Garnis" , song: "My First Kiss", season:7, style:"Cha-cha-cha", dancer_id: 146, partner_id:13)
Performance.create!(dancer_name:"Robert Roldan" ,partner:"Kathryn McCormick" , song: "Heaven is a Place on Earth", season:7, style:"Contemporary", dancer_id: 194, partner_id: 143 )
Performance.create!(dancer_name:"Courtney Galiliano" ,partner:"AdéChiké Torbert  " , song: "Manteca", season:7, style:"Jazz", dancer_id: 45, partner_id:3 )
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Jose Ruiz" , song: "Try a Little Tenderness", season:7, style:"Hip-hop", dancer_id: 44, partner_id:134 )
Performance.create!(dancer_name:"Lauren Froderman" ,partner:"Allison Holker" , song: "Who's Got the Pain", season:7, style:"Broadway", dancer_id: 151, partner_id:10 )
Performance.create!(dancer_name:"Billy Bell" ,partner:"Ade Obayomi" , song: "Mad World", season:7, style:"Contemporary", dancer_id: 20, partner_id:2 )
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Jose Ruiz" , song: "From this Moment On", season:7, style:"Broadway", dancer_id: 146, partner_id:134 )
Performance.create!(dancer_name:"Lauren Froderman" ,partner:"AdéChiké Torbert " , song: "Fever", season:7, style:"Foxtrot", dancer_id:151, partner_id:3 )
Performance.create!(dancer_name:"Billy Bell" ,partner:"Robert Roldan" , song: "Ganesh", season:7, style:"Bollywood", dancer_id: 20, partner_id:194 )
Performance.create!(dancer_name:"Lauren Froderman" ,partner:"Pasha Kovalev" , song: "Oblivion", season:7, style:"Argentine Tango", dancer_id: 151, partner_id:138)
Performance.create!(dancer_name:"Lauren Gottlieb" ,partner:"AdéChiké Torbert " , song: "The Path", season:7, style:"African Jazz", dancer_id: 152, partner_id:3 )
Performance.create!(dancer_name:"Robert Roldan" ,partner:"Anya Garnis" , song: "Lost", season:7, style:"Viennese Waltz", dancer_id:194, partner_id: 13)
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Courtney Galiano" , song: "When Love Takes Over", season:7, style:"Disco", dancer_id: 146, partner_id:35 )
Performance.create!(dancer_name:"Lauren Froderman" ,partner:"Ade Obayomi" , song: "Hide U", season:7, style:"Jazz", dancer_id: 151, partner_id: 2)
Performance.create!(dancer_name:"Kathryn McCormick" ,partner:"AdéChiké Torbert " , song: "Fearless Love", season:7, style:"Contemporary", dancer_id: 143, partner_id:3 )
Performance.create!(dancer_name:"Robert Roldan" ,partner:"Dominic Sandoval" , song: "Scars", season:7, style:"Hip-hop", dancer_id: 194, partner_id:54 )
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Neil Haskell" , song: "How It Ends", season:7, style:"Contemporary", dancer_id:146, partner_id:178 )
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Lauren Gottlieb" , song: "Om Mangalam", season:7, style:"Bollywood", dancer_id: 145, partner_id:152)
Performance.create!(dancer_name:"Twitch Boss" ,partner:"Lauren Froderman" , song: "Power", season:7, style:"Hip-hop", dancer_id: 206, partner_id: 151)
Performance.create!(dancer_name:"Mark Kanemura" ,partner:"Robert Roldan" , song: "Whip It", season:7, style:"Jazz", dancer_id: 156, partner_id:194)
Performance.create!(dancer_name:"Lauren Froderman" ,partner:"Robert Roldan" , song: "That Home", season:7, style:"Contemporary", dancer_id: 151, partner_id:194 )
Performance.create!(dancer_name:"Lauren Froderman" ,partner:"Kent Boyd" , song: "Hip to be Square", season:7, style:"Jazz", dancer_id: 151, partner_id:146 )
Performance.create!(dancer_name:"Allison Holker" ,partner:"Kent Boyd" , song: "Sundrenched World", season:7, style:"Contemporary", dancer_id: 10, partner_id:146 )
Performance.create!(dancer_name:"Kathryn McCormick" ,partner:"Robert Roldan" , song: "Cool", season:7, style:"Broadway", dancer_id: 143, partner_id:194 )
Performance.create!(dancer_name:"Lauren Froderman" ,partner:"Pasha Kovalev" , song: "Not Myself Tonight", season:7, style:"Cha-cha-cha", dancer_id: 151, partner_id:138 )
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Robert Roldan" , song: "The Chosen/Drum Addict", season:7, style:"Malevos", dancer_id: 146, partner_id:194 )
