Performance.create!(dancer_name: "Billy Bell", partner: "Lauren Gottileb", song: "Footloose", season: 7, style: "Broadway", dancer_id: 29, partner_id:152 )
Performance.create!(dancer_name: "Comfort Fedoke", partner: "Jose Ruiz", song: "Beautiful Monster", season: 7, style: "Hip-Hop", dancer_id: 44, partner_id:134 )
Performance.create!(dancer_name: "Kathryn McCormick", partner: "AdéChiké Torbert ", song: " Addicted to Love", season: 7, style: "Jazz", dancer_id: 96, partner_id:3 )
Performance.create!(dancer_name: "Pasha Kovalev", partner: "Melinda Sullivan ", song: "L-O-V-E", season: 7, style: "Jive", dancer_id: 138, partner_id: 165)
Performance.create!(dancer_name: "Allison Holker", partner: "Alex Wong", song: "Hallelujah", season: 7, style: "Contemporary", dancer_id: 10, partner_id:5 )
Performance.create!(dancer_name: "Alexie Agdeppa", partner: "Twitch Boss", song: "Butterfly", season: 7, style: "Hip-Hop", dancer_id: 8, partner_id:206 )
Performance.create!(dancer_name: "Lauren Froderman", partner: "Ade Obayomi", song: "Oh Yeah", season: 7, style: "Pop-Jazz", dancer_id: 151, partner_id:2 )
Performance.create!(dancer_name: "Kent Boyd", partner: "Anya Garnis", song: "Lady Marmalade", season: 7, style: "Cha-cha=cha", dancer_id: 146, partner_id:13 )
Performance.create!(dancer_name: "Ashley Galvan", partner: "Neil Haskell", song: "For All We Know", season: 7, style: "Contemporary", dancer_id: 20, partner_id:178 )
Performance.create!( dancer_name: "Courtney Galiano", partner: "Robert Roldan", song: "Norweg", season: 7, style: "African Jazz", dancer_id: 45, partner_id: 194)
Performance.create!( dancer_name: "Pasha Kovalev", partner: "Christina Santana", song: "Ira Deorum/Sanctus", season: 7, style: "Paso Doble", dancer_id: 138, partner_id:nil )
Performance.create!( dancer_name: "Allison Holker", partner: "AdéChiké Torbert", song: "Listen to Your Heart", season: 7, style: "Contemporary", dancer_id: 10, partner_id:3 )
Performance.create!( dancer_name: "Lauren Gottlieb", partner: "Alex Wong", song: "Summertime", season: 7, style: "Broadway", dancer_id: 152, partner_id: 194 )
Performance.create!( dancer_name: "Anya Garnis", partner: "Robert Roldan", song: "Argentine Tango", season: 7, style: "Argentine Tango", dancer_id: 13, partner_id:194 )
Performance.create!( dancer_name: "Ade Obayomi", partner: "Melinda Sullivan", song: "Squander", season: 7, style: "Contemporary", dancer_id: 2, partner_id:165 )
Performance.create!( dancer_name: "Kathryn McCormick", partner: "Jose Ruiz", song: "Marjaani Marjaani Kasama", season: 7, style: "Bollywood", dancer_id: 96, partner_id:134 )
Performance.create!( dancer_name: "Lauren Froderman", partner: "Dominic Sandoval", song: "If I Were a Boy", season: 7, style: "Lyrical Hip-Hop", dancer_id: 151, partner_id: )
Performance.create!( dancer_name: "Kent Boyd", partner: "Courtney Gailiano", song: "Amy Amy Amy", season: 7, style: "Jazz", dancer_id: 146, partner_id:45 )
Performance.create!( dancer_name: "Lauren Gottlieb", partner: "AdéChiké Torbert ", song: "Hot-N-Fun", season: 7, style: "Hip-Hop", dancer_id: 152, partner_id:3 )
Performance.create!( dancer_name: "Kent Boyd", partner: "Courtney Gailiano", song: "Amy Amy Amy", season: 7, style: "Jazz", dancer_id: 146, partner_id:45 )
Performance.create!( dancer_name: "Lauren Gottlieb", partner: "AdéChiké Torbert ", song: "Hot-N-Fun", season: 7, style: "Hip-Hop", dancer_id: 152, partner_id:3 )
Performance.create!( dancer_name: "Ashley Galvan", partner: "Ade Obayomi", song: "Cosmic Love", season: 7, style: "Contemporary", dancer_id: 20, partner_id:2 )
Performance.create!( dancer_name: "Courtney Galiano", partner: "Robert Roldan", song: "XXXO", season: 7, style: "Jazz", dancer_id: 45, partner_id:194 )
Performance.create!( dancer_name: "Pasha Kovalev", partner: "Melinda Sullivan", song: "Magdelena, Mi Amor", season: 7, style: "Salsa", dancer_id: 138, partner_id:165 )
Performance.create!( dancer_name: "Lauren Froderman", partner: "Neil Haskell", song: "Let me Entertain You", season: 7, style: "Broadway", dancer_id: 151, partner_id:178 )
Performance.create!(dancer_name: "Billy Bell", partner: "Kathryn McCormick", song: "Jar of Hearts", season: 7, style: "Contemporary", dancer_id: 29, partner_id:143 )
Performance.create!( dancer_name: "Anya Garnis", partner: "Jose Ruiz", song: "Long Time", season: 7, style: "Samba", dancer_id: 13, partner_id: 134)
Performance.create!( dancer_name: "Kent Boyd", partner: "Allison Holker", song: "Heartburn", season: 7, style: "Jazz", dancer_id: 146, partner_id:10 )
Performance.create!( dancer_name: "Alex Wong", partner: "Twitch Boss", song: "Hip-Hop", season: 7, style: "Hip-Hop", dancer_id: 5, partner_id: 206 )
Performance.create!(dancer_name:"Lauren Froderman" ,partner:"Pasha Kovalev" , song: "Telephone", season:7, style:"Cha-cha-cha", dancer_id: 151, partner_id:138)

Performance.create!(dancer_name:"Lauren Gottileb" ,partner:"Jose Ruiz" , song: "Never Tear us Apart", season:7, style:"Contemporary", dancer_id:152, partner_id:134 )
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Comfort Fedoke" , song: "You're not my Girl", season:7, style:"Hip-hop", dancer_id:146, partner_id:44 )
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"AdéChiké Torbert  " , song: "Is You or is You Ain't my Baby", season:7, style:"Jazz", dancer_id:45, partner_id:3 )
Performance.create!(dancer_name:"Billy Bell" ,partner:"Katee Shean" , song: "Broadway", season:7, style:"Broadway", dancer_id: 29, partner_id:142)
Performance.create!(dancer_name:"Ashley Galvan" ,partner:"Dominic Sandoval" , song: "How Low", season:7, style:"Hip-hop", dancer_id: 20, partner_id:54 )
Performance.create!(dancer_name:"Kathyrn McCormick" ,partner:"Robert Roldan" , song: "Sinking Feeling", season:7, style:"Jazz", dancer_id:143, partner_id: 194 )
Performance.create!(dancer_name:"AdéChiké Torbert  " ,partner:"Maria" , song: "Mourya Re", season:7, style:"Bollywood", dancer_id:3, partner_id: nil)
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Lauren Froderman" , song: "Collide", season:7, style:"Contemporary", dancer_id: 146, partner_id:151 )
Performance.create!(dancer_name:"Ashely Galvan" ,partner:"Robert Roldan" , song: "Man with the Hex", season:7, style:"Quickstep", dancer_id:20, partner_id: 194)
Performance.create!(dancer_name:"Billy Bell" ,partner:"Jose Ruiz" , song: "The Hunt", season:7, style:"African Jazz", dancer_id: 29, partner_id:134)
Performance.create!(dancer_name:"Lauren Foderman" ,partner:"Mark Kanemura" , song: "Jungle", season:7, style:"Tahitan", dancer_id: 151, partner_id: 156)
Performance.create!(dancer_name:"Anya Garnis" ,partner:"AdéChiké Torbert " , song: "Oyelo Que Te Convience", season:7, style:"Salsa", dancer_id: 13, partner_id:3)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Jose Ruiz" , song: "Mister Cellophane", season:7, style:"Broadway", dancer_id: 45, partner_id:134 )
Performance.create!(dancer_name:"Allison Holker" ,partner:"Robert Roldan" , song: "Fix you", season:7, style:"Contemporary", dancer_id: 10, partner_id: 194)
Performance.create!(dancer_name:"Billy Bell" ,partner:"Anya Garnis" , song: "Paradise by the Dashboard Light", season:7, style:"Jive", dancer_id: 20, partner_id:13)
Performance.create!(dancer_name:"Kent Boyd " ,partner:" Neil Haskell" , song: "Shoeless Joe from Hannibal, MO", season:7, style:"Broadway", dancer_id:146, partner_id: )
Performance.create!(dancer_name:"Billy Bell" ,partner:"Lauren Froderman" , song: "Boogie Shoes", season:7, style:"Jazz", dancer_id: 20, partner_id:151 )
Performance.create!(dancer_name:"Jose Ruiz" ,partner:"Dominic Sandoval" , song: "Battle for the Beat", season:7, style:"B-Boying", dancer_id:134, partner_id: 134)
Performance.create!(dancer_name:"Kent Boyd" ,partner:"AdéChiké Torbert " , song: "You only Disappear", season:7, style:"Contemporary", dancer_id:146, partner_id: )
Performance.create!(dancer_name:"Robert Roldan" ,partner:"Kathyrn McCormick" , song: "Instant Replay", season:7, style:"Disco", dancer_id:194, partner_id:143 )
Performance.create!(dancer_name:"Twitch Boss" ,partner:"Lauren Froderman" , song: "My Chick Bad", season:7, style:"Hip-hop", dancer_id: 206, partner_id:151)
Performance.create!(dancer_name:"Allison Holker" ,partner:"Jose Ruiz" , song: "Eternal Sunshine of the Mind theme", season:7, style:"Contemporary", dancer_id:10, partner_id:134 )
Performance.create!(dancer_name:"Lauren Gottileb" ,partner:"Robert Roldan" , song: "Wasted Time", season:7, style:"Jazz", dancer_id: 152, partner_id: 194 )
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Kathryn McCormick" , song: "Tightrope", season:7, style:"Jazz", dancer_id:146, partner_id:143 )
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"AdéChiké Torbert  " , song: "Fallin", season:7, style:"Lyrical Hip-hop", dancer_id: 44, partner_id:3 )
Performance.create!(dancer_name:"Lauren Froderman" ,partner:"Robert Roldan" , song: "Drummer Boy", season:7, style:"Samba", dancer_id: 151, partner_id:194 )
Performance.create!(dancer_name:"Jose Ruiz" ,partner:"AdéChiké Torbert " , song: "The Arrival", season:7, style:"Paso Doble", dancer_id: 134, partner_id:3 )
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Twitch Boss" , song: "Pro Nails", season:7, style:"Stepping", dancer_id: 146, partner_id:206 )
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Anya Garnis" , song: "My First Kiss", season:7, style:"Cha-cha-cha", dancer_id: 146, partner_id:13)
Performance.create!(dancer_name:"Robert Roldan" ,partner:"Kathryn McCormick" , song: "Heaven is a Place on Earth", season:7, style:"Contemporary", dancer_id: 194, partner_id: 143 )
Performance.create!(dancer_name:"Courtney Galiliano" ,partner:"AdéChiké Torbert  " , song: "Manteca", season:7, style:"Jazz", dancer_id: 45, partner_id:3 )
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Jose Ruiz" , song: "Try a Little Tenderness", season:7, style:"Hip-hop", dancer_id: 44, partner_id:134 )
Performance.create!(dancer_name:"Lauren Froderman" ,partner:"Allison Holker" , song: "Who's Got the Pain", season:7, style:"Broadway", dancer_id: 151, partner_id:10 )
Performance.create!(dancer_name:"Billy Bell" ,partner:"Ade Obayomi" , song: "Mad World", season:7, style:"Contemporary", dancer_id: 20, partner_id:2 )
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Jose Ruiz" , song: "From this Moment On", season:7, style:"Broadway", dancer_id: 146, partner_id:134 )
Performance.create!(dancer_name:"Lauren Froderman" ,partner:"AdéChiké Torbert " , song: "Fever", season:7, style:"Foxtrot", dancer_id:151, partner_id:3 )
Performance.create!(dancer_name:"Billy Bell" ,partner:"Robert Roldan" , song: "Ganesh", season:7, style:"Bollywood", dancer_id: 20, partner_id:194 )
Performance.create!(dancer_name:"Lauren Froderman" ,partner:"Pasha Kovalev" , song: "Oblivion", season:7, style:"Argentine Tango", dancer_id: 151, partner_id:138)
Performance.create!(dancer_name:"Lauren Gottlieb" ,partner:"AdéChiké Torbert " , song: "The Path", season:7, style:"African Jazz", dancer_id: 152, partner_id:3 )
Performance.create!(dancer_name:"Robert Roldan" ,partner:"Anya Garnis" , song: "Lost", season:7, style:"Viennese Waltz", dancer_id:194, partner_id: 13)
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Courtney Galiano" , song: "When Love Takes Over", season:7, style:"Disco", dancer_id: 146, partner_id:35 )
Performance.create!(dancer_name:"Lauren Froderman" ,partner:"Ade Obayomi" , song: "Hide U", season:7, style:"Jazz", dancer_id: 151, partner_id: 2)
Performance.create!(dancer_name:"Kathryn McCormick" ,partner:"AdéChiké Torbert " , song: "Fearless Love", season:7, style:"Contemporary", dancer_id: 143, partner_id:3 )
Performance.create!(dancer_name:"Robert Roldan" ,partner:"Dominic Sandoval" , song: "Scars", season:7, style:"Hip-hop", dancer_id: 194, partner_id:54 )
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Neil Haskell" , song: "How It Ends", season:7, style:"Contemporary", dancer_id:146, partner_id:178 )
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Lauren Gottlieb" , song: "Om Mangalam", season:7, style:"Bollywood", dancer_id: 145, partner_id:152)
Performance.create!(dancer_name:"Twitch Boss" ,partner:"Lauren Froderman" , song: "Power", season:7, style:"Hip-hop", dancer_id: 206, partner_id: 151)
Performance.create!(dancer_name:"Mark Kanemura" ,partner:"Robert Roldan" , song: "Whip It", season:7, style:"Jazz", dancer_id: 156, partner_id:194)
Performance.create!(dancer_name:"Lauren Froderman" ,partner:"Robert Roldan" , song: "That Home", season:7, style:"Contemporary", dancer_id: 151, partner_id:194 )
Performance.create!(dancer_name:"Lauren Froderman" ,partner:"Kent Boyd" , song: "Hip to be Square", season:7, style:"Jazz", dancer_id: 151, partner_id:146 )
Performance.create!(dancer_name:"Allison Holker" ,partner:"Kent Boyd" , song: "Sundrenched World", season:7, style:"Contemporary", dancer_id: 10, partner_id:146 )
Performance.create!(dancer_name:"Kathryn McCormick" ,partner:"Robert Roldan" , song: "Cool", season:7, style:"Broadway", dancer_id: 143, partner_id:194 )
Performance.create!(dancer_name:"Lauren Froderman" ,partner:"Pasha Kovalev" , song: "Not Myself Tonight", season:7, style:"Cha-cha-cha", dancer_id: 151, partner_id:138 )
Performance.create!(dancer_name:"Kent Boyd" ,partner:"Robert Roldan" , song: "The Chosen/Drum Addict", season:7, style:"Malevos", dancer_id: 146, partner_id:194 )

Performance.create!(dancer_name:"Rayven Armijo" ,partner:"Jamie Bayard" , song: "American Boy", season:4, style:"Hip-Hop", dancer_id: 191 , partner_id: 69)
Performance.create!(dancer_name:"Susie Garcia" ,partner:"Marquis Cunningham" , song: "Dark Waltz", season:4, style:"Waltz", dancer_id: 198 , partner_id:158)
Performance.create!(dancer_name:"Kourtni Lind" ,partner:"Matt Dorame" , song: "Tainted Love", season:4, style:"Jazz", dancer_id:148 , partner_id:160)
Performance.create!(dancer_name:"Chelsea Traille" ,partner:"Thayne Jasperson" , song: "Oye Como Va", season:4, style:"Cha-cha-cha", dancer_id:38 , partner_id:200)
Performance.create!(dancer_name:"Chelsie Hightower" ,partner:"Mark Kanemura" , song: "Beautiful", season:4, style:"Contemporary", dancer_id:39 , partner_id:156)
Performance.create!(dancer_name:"Kherington Payne" ,partner:"Twitch Boss" , song: "Too Damn Hot", season:4, style:"Broadway", dancer_id:147 , partner_id: 206)
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Chris Jarosz" , song: "Boom Boom", season:4, style:"Jive", dancer_id: 44, partner_id:)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Joshua Allen" , song: "No Air", season:4, style:"Lyrical hip-hop", dancer_id: 142, partner_id:135)
Performance.create!(dancer_name:"Jessica King" ,partner:"William Wingfield" , song: "Tango", season:4, style:"Tango", dancer_id:128 , partner_id:211)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Gev Manoukian" , song: "Boogie Wonderland", season:4, style:"Disco", dancer_id:45 , partner_id:62)
Performance.create!(dancer_name:"Chelsea Traille" ,partner:"Thayne Jasperson" , song: "Untouched", season:4, style:"Jazz", dancer_id: 38 , partner_id:200)
Performance.create!(dancer_name:"Chelsie Hightower" ,partner:"Mark Kanemura" , song: "Mi Confesion", season:4, style:"Argentine Tango", dancer_id: 39 , partner_id: 156)
Performance.create!(dancer_name:"Jessica King" ,partner:"William Wingfield" , song: "Whatever U Like", season:4, style:"Hip-Hop", dancer_id:128 , partner_id:211)
Performance.create!(dancer_name:"Kourtni Lind" ,partner:"Matt Dorame" , song: "A Foggy Day (In London Town)", season:4, style:"Foxtrot", dancer_id:148 , partner_id:160)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Gev Manoukian" , song: "Lost", season:4, style:"Contemporary", dancer_id:45 , partner_id:62)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Joshua Allen" , song: "All for the Best", season:4, style:"Broadway", dancer_id:142 , partner_id:135)
Performance.create!(dancer_name:"Susie Garcia" ,partner:"Marquis Cunningham" , song: "Aguanile", season:4, style:"Salsa", dancer_id: 198, partner_id:158)
Performance.create!(dancer_name:"Kherington Payne" ,partner:"Twitch Boss" , song: "A New Day Has Come", season:4, style:"Viennese Waltz", dancer_id:147 , partner_id:206)
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Chris Jarosz" , song: "Come and Get Me", season:4, style:"Krump", dancer_id:44, partner_id:)
Performance.create!(dancer_name:"Kherington Payne" ,partner:"Twitch Boss" , song: "Don't Touch Me", season:4, style:"Hip-hop", dancer_id:147 , partner_id:206)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Gev Manoukian" , song: "Wishing on a Star", season:4, style:"Rumba", dancer_id:45 , partner_id:62)
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Chris Jarosz" , song: "The Beautiful People", season:4, style:"Afro Jazz", dancer_id:44 , partner_id:)
Performance.create!(dancer_name:"Jessica King" ,partner:"William Wingfield" , song: "Heaven Must Have Sent you", season:4, style:"Disco", dancer_id:128 , partner_id:211)
Performance.create!(dancer_name:"Kourtni Lind" ,partner:"Matt Dorame" , song: "Wrestlers", season:4, style:"Contemporary", dancer_id:148 , partner_id:160)
Performance.create!(dancer_name:"Chelsea Traille" ,partner:"Thayne Jasperson" , song: "You Can't Hurry Love", season:4, style:"Quickstep", dancer_id:38 , partner_id:200)
Performance.create!(dancer_name:"Chelsie Hightower" ,partner:"Mark Kanemura" , song: "Bleeding Love", season:4, style:"Lyrical Hip-hop", dancer_id: 39 , partner_id: 156)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Joshua Allen" , song: "Baila, Baila", season:4, style:"Samba", dancer_id:142 , partner_id:135)
Performance.create!(dancer_name:"Jessica King" ,partner:"William Wingfield" , song: "Choo Choo Ch'Boogie", season:4, style:"Jive", dancer_id: 128 , partner_id:211)
Performance.create!(dancer_name:"Jessica King" ,partner:"William Wingfield" , song: "Alone", season:4, style:"Lyrical Jazz", dancer_id:128 , partner_id:211)
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Thayne Jasperson" , song: "Cool", season:4, style:"Broadway", dancer_id:44 , partner_id:200)
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Thayne Jasperson" , song: "Hov Arek Sarer Jan", season:4, style:"Smooth Waltz", dancer_id:44 , partner_id:200)
Performance.create!(dancer_name:"Kourtni Lind" ,partner:"Matt Dorame" , song: "How Do I Breathe", season:4, style:"Hip-hop", dancer_id:148 , partner_id:160)
Performance.create!(dancer_name:"Kourtni Lind" ,partner:"Matt Dorame" , song: "Ban Com Tim", season:4, style:"Mambo", dancer_id:148 , partner_id:160)
Performance.create!(dancer_name:"Chelsie Hightower" ,partner:"Mark Kanemura" , song: "Kiss Kiss", season:4, style:"Jazz", dancer_id: 39 , partner_id: 156)
Performance.create!(dancer_name:"Chelsie Hightower" ,partner:"Mark Kanemura" , song: "It's my Life", season:4, style:"Foxtrot", dancer_id: 39 , partner_id: 156)
Performance.create!(dancer_name:"Kherington Payne" ,partner:"Twitch Boss" , song: "Malaguena", season:4, style:"Paso Doble", dancer_id:147 , partner_id:206)
Performance.create!(dancer_name:"Kherington Payne" ,partner:"Twitch Boss" , song: "Dreaming with a Broken Heart", season:4, style:"Contemporary", dancer_id:147 , partner_id: 206)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Joshua Allen" , song: "Hometown Glory", season:4, style:"Contemporary", dancer_id:142 , partner_id:135)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Joshua Allen" , song: "Shake it", season:4, style:"West Coast Swing", dancer_id: 142, partner_id:135)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Gev Manoukian" , song: "Lights, Camera, Action!", season:4, style:"Hip-hop", dancer_id:45 , partner_id:62)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Gev Manoukian" , song: "New York, New York", season:4, style:"Broadway", dancer_id:45 , partner_id:62)
Performance.create!(dancer_name:"Chelsie Hightower" ,partner:"Mark Kanemura" , song: "Fuego", season:4, style:"Salsa", dancer_id: 39 , partner_id: 156)
Performance.create!(dancer_name:"Mark Kanemura" ,partner:"Chelsie Hightower" , song: "I'm a Woman", season:4, style:"Broadway", dancer_id:156 , partner_id: 39)
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Thayne Jasperson" , song: "Can We Chill", season:4, style:"Hip-hop", dancer_id: 44, partner_id:200)
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Thayne Jasperson" , song: "A Different Corner", season:4, style:"Contemporary", dancer_id:44 , partner_id:200)
Performance.create!(dancer_name:"Jessica King" ,partner:"William Wingfield" , song: "Silence", season:4, style:"Contemporary", dancer_id:128 , partner_id:211)
Performance.create!(dancer_name:"William Wingfield" ,partner:"Jessica King" , song: "Bandstand Boogie", season:4, style:"Quickstep", dancer_id:211 , partner_id:128)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Gev Manoukian" , song: "Don't stop the Music", season:4, style:"Cha-cha-cha", dancer_id:45 , partner_id:62)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Gev Manoukian" , song: "Standing There", season:4, style:"Jazz", dancer_id: 45 , partner_id:62)
Performance.create!(dancer_name:"Kherington Payne" ,partner:"Twitch Boss" , song: "2 Buck 4 TV", season:4, style:"Krump", dancer_id:147 , partner_id: 206)
Performance.create!(dancer_name:"Kherington Payne" ,partner:"Twitch Boss" , song: "Assassin's Tango", season:4, style:"Tango", dancer_id:147 , partner_id: 206)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Joshua Allen" , song: "Iris", season:4, style:"Vienesse Waltz", dancer_id:142 , partner_id:135)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Joshua Allen" , song: "Dhoom Taana", season:4, style:"Bollywood", dancer_id:142 , partner_id:135)
Performance.create!(dancer_name:"Courtney Gailiano" ,partner:"Joshua Allen" , song: "Skippin", season:4, style:"Hip-hop", dancer_id:45 , partner_id:135)
Performance.create!(dancer_name:"Courtney Gailiano" ,partner:"Joshua Allen" , song: "Hero", season:4, style:"Rumba", dancer_id:45 , partner_id:135)
Performance.create!(dancer_name:"Kherington Payne" ,partner:"Mark Kanemura" , song: "Kick Back", season:4, style:"Country-western two step", dancer_id:147 , partner_id: 156)
Performance.create!(dancer_name:"Mark Kanemura" ,partner:"Kherington Payne" , song: "Canned Heat", season:4, style:"Jazz", dancer_id: 156 , partner_id:147)
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Twitch Boss" , song: "Open Arms", season:4, style:"Smooth Waltz", dancer_id:44 , partner_id:206)
Performance.create!(dancer_name:"Twitch Boss" ,partner:"Comfort Fedoke" , song: "Forever", season:4, style:"Hip-hop", dancer_id: 206, partner_id:44)
Performance.create!(dancer_name:"Katee Shean" ,partner:"William Wingfield" , song: "Sit Down You're Rocking the Boat", season:4, style:"Broadway", dancer_id:142 , partner_id:211)
Performance.create!(dancer_name:"Katee Shean" ,partner:"William Wingfield" , song: "Imagine", season:4, style:"Pas de deux", dancer_id: 142, partner_id:211)
Performance.create!(dancer_name:"Chelsie Hightower" ,partner:"Gev Manoukian" , song: "The House is Rockin", season:4, style:"Jive", dancer_id: 39 , partner_id:62)
Performance.create!(dancer_name:"Gev Manoukian" ,partner:"Chelsie Hightower" , song: "These Arms of Mine", season:4, style:"Contemporary", dancer_id: 62, partner_id: 39)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"William Wingfield" , song: "I  Fell in Love with a DJ", season:4, style:"Samba", dancer_id:45 , partner_id:)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"William Wingfield" , song: "Like You'll Never See Me Again", season:4, style:"Lyrical Hip-hop", dancer_id:45 , partner_id:)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Twitch Boss" , song: "Mercy", season:4, style:"Contemporary", dancer_id:142 , partner_id: 206)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Twitch Boss" , song: "Sweet Georgia Brown", season:4, style:"Broadway", dancer_id:142 , partner_id: 206)
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Mark Kanemura" , song: "Party People", season:4, style:"Hip-hop", dancer_id:44 , partner_id: 156)
Performance.create!(dancer_name:"Mark Kanemura" ,partner:"Comfort Fedoke" , song: "Lady Luck", season:4, style:"Foxtrot", dancer_id: 156 , partner_id:44)
Performance.create!(dancer_name:"Joshua Allen" ,partner:"Chelsie Hightower" , song: "A Los Amigos", season:4, style:"Argentine Tango", dancer_id: 39, partner_id: 135)
Performance.create!(dancer_name:"Chelsie Hightower" ,partner:"Joshua Allen" , song: "Everlasting Love", season:4, style:"Disco", dancer_id: 39 , partner_id:135)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Mark Kanemura" , song: "The Time of My Life", season:4, style:"Viennese Waltz", dancer_id:45 , partner_id: 156)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Mark Kanemura" , song: "The Garden", season:4, style:"Jazz", dancer_id:45 , partner_id: 156)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Joshua Allen" , song: "All By Myself", season:4, style:"Contemporary", dancer_id:142 , partner_id:135)
Performance.create!(dancer_name:"Joshua Allen" ,partner:"Katee Shean" , song: "Filet", season:4, style:"Paso Doble", dancer_id:135 , partner_id:)
Performance.create!(dancer_name:"Chelsie Hightower" ,partner:"Twitch Boss" , song: "Ahora Me Toca a Mi", season:4, style:"Mambo", dancer_id: 39, partner_id: 206)
Performance.create!(dancer_name:"Twitch Boss" ,partner:"Chelsie Hightower" , song: "Control", season:4, style:"Hip-hop", dancer_id: 206 , partner_id:39)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Twitch Boss" , song: "Church", season:4, style:"Hip-hop", dancer_id:45 , partner_id:)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Joshua Allen" , song: "Slow Dancing in a Burning Room", season:4, style:"Lyrical Jazz", dancer_id:142 , partner_id:135)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Katee Shean" , song: "The Trolley Song", season:4, style:"Broadway", dancer_id: 45, partner_id:142)
Performance.create!(dancer_name:"Joshua Allen" ,partner:"Twitch Boss" , song: "Trepak", season:4, style:"Trepak", dancer_id:135 , partner_id: 206)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Twitch Boss" , song: "Feeling Good", season:4, style:"Foxtrot", dancer_id:142 , partner_id: 206)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Joshua Allen" , song: "The Dirty Boogie", season:4, style:"Jive", dancer_id:45 , partner_id:135)
