# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# Performance.create!(name:"Lauren Froderman" ,partner:"Pasha Kovalev" , song: "Telephone", season:7, style:"Cha-cha-cha", dancer_id: 151)
# Performance.create!(name:"Lauren Gottileb" ,partner:"Jose Ruiz" , song: "Never Tear us Apart", season:7, style:"Contemporary", dancer_id:152 )
# Performance.create!(name:"Kent Boyd" ,partner:"Comfort Fedoke" , song: "You're not my Girl", season:7, style:"Hip-hop", dancer_id:146 )
# Performance.create!(name:"Courtney Galiano" ,partner:"AdéChiké Torbert  " , song: "Is You or is You Ain't my Baby", season:7, style:"Jazz", dancer_id:45 )
# Performance.create!(name:"Billy Bell" ,partner:"Katee Shean" , song: "Broadway", season:7, style:"Broadway", dancer_id: 29)
# Performance.create!(name:"Ashley Galvan" ,partner:"Dominic Sandoval" , song: "How Low", season:7, style:"Hip-hop", dancer_id: 20 )
# Performance.create!(name:"Kathyrn McCormick" ,partner:"Robert Roldan" , song: "Sinking Feeling", season:7, style:"Jazz", dancer_id:143 )
# Performance.create!(name:"AdéChiké Torbert  " ,partner:"Maria" , song: "Mourya Re", season:7, style:"Bollywood", dancer_id:3 )
# Performance.create!(name:"Kent Boyd" ,partner:"Lauren Froderman" , song: "Collide", season:7, style:"Contemporary", dancer_id: 146 )
# Performance.create!(name:"Ashely Galvan" ,partner:"Robert Roldan" , song: "Man with the Hex", season:7, style:"Quickstep", dancer_id:20 )
# Performance.create!(name:"Billy Bell" ,partner:"Jose Ruiz" , song: "The Hunt", season:7, style:"African Jazz", dancer_id: 29 )
# Performance.create!(name:"Lauren Foderman" ,partner:"Mark Kanemura" , song: "Jungle", season:7, style:"Tahitan", dancer_id: 151 )
# Performance.create!(name:"Anya Garnis" ,partner:"AdéChiké Torbert " , song: "Oyelo Que Te Convience", season:7, style:"Salsa", dancer_id: 13)
# Performance.create!(name:"Courtney Galiano" ,partner:"Jose Ruiz" , song: "Mister Cellophane", season:7, style:"Broadway", dancer_id: 45 )
# Performance.create!(name:"Allison Holker" ,partner:"Robert Roldan" , song: "Fix you", season:7, style:"Contemporary", dancer_id: 10 )
# Performance.create!(name:"Billy Bell" ,partner:"Anya Garnis" , song: "Paradise by the Dashboard Light", season:7, style:"Jive", dancer_id: 20)
# Performance.create!(name:"Kent Boyd " ,partner:" Neil Haskell" , song: "Shoeless Joe from Hannibal, MO", season:7, style:"Broadway", dancer_id:146 )
# Performance.create!(name:"Billy Bell" ,partner:"Lauren Froderman" , song: "Boogie Shoes", season:7, style:"Jazz", dancer_id: 20 )
# Performance.create!(name:"Jose Ruiz" ,partner:"Dominic Sandoval" , song: "Battle for the Beat", season:7, style:"B-Boying", dancer_id:134 )
# Performance.create!(name:"Kent Boyd" ,partner:"AdéChiké Torbert " , song: "You only Disappear", season:7, style:"Contemporary", dancer_id:146 )
# Performance.create!(name:"Robert Roldan" ,partner:"Kathyrn McCormick" , song: "Instant Replay", season:7, style:"Disco", dancer_id:194 )
# Performance.create!(name:"Twitch Boss" ,partner:"Lauren Froderman" , song: "My Chick Bad", season:7, style:"Hip-hop", dancer_id: 206)
# Performance.create!(name:"Allison Holker" ,partner:"Jose Ruiz" , song: "Eternal Sunshine of the Mind theme", season:7, style:"Contemporary", dancer_id:10 )
# Performance.create!(name:"Lauren Gottileb" ,partner:"Robert Roldan" , song: "Wasted Time", season:7, style:"Jazz", dancer_id: 152 )
# Performance.create!(name:"Kent Boyd" ,partner:"Kathryn McCormick" , song: "Tightrope", season:7, style:"Jazz", dancer_id:146 )
# Performance.create!(name:"Comfort Fedoke" ,partner:"AdéChiké Torbert  " , song: "Fallin", season:7, style:"Lyrical Hip-hop", dancer_id: 44 )
# Performance.create!(name:"Lauren Froderman" ,partner:"Robert Roldan" , song: "Drummer Boy", season:7, style:"Samba", dancer_id: 151 )
# Performance.create!(name:"Jose Ruiz" ,partner:"AdéChiké Torbert " , song: "The Arrival", season:7, style:"Paso Doble", dancer_id: 134 )
# Performance.create!(name:"Kent Boyd" ,partner:"Twitch Boss" , song: "Pro Nails", season:7, style:"Stepping", dancer_id: 146 )
# Performance.create!(name:"Kent Boyd" ,partner:"Anya Garnis" , song: "My First Kiss", season:7, style:"Cha-cha-cha", dancer_id: 146)
# Performance.create!(name:"Robert Roldan" ,partner:"Kathryn McCormick" , song: "Heaven is a Place on Earth", season:7, style:"Contemporary", dancer_id: 194 )
# Performance.create!(name:"Courtney Galiliano" ,partner:"AdéChiké Torbert  " , song: "Manteca", season:7, style:"Jazz", dancer_id: 45 )
# Performance.create!(name:"Comfort Fedoke" ,partner:"Jose Ruiz" , song: "Try a Little Tenderness", season:7, style:"Hip-hop", dancer_id: 44 )
# Performance.create!(name:"Lauren Froderman" ,partner:"Allison Holker" , song: "Who's Got the Pain", season:7, style:"Broadway", dancer_id: 151 )
# Performance.create!(name:"Billy Bell" ,partner:"Ade Obayomi" , song: "Mad World", season:7, style:"Contemporary", dancer_id: 20 )
# Performance.create!(name:"Kent Boyd" ,partner:"Jose Ruiz" , song: "From this Moment On", season:7, style:"Broadway", dancer_id: 146 )
# Performance.create!(name:"Lauren Froderman" ,partner:"AdéChiké Torbert " , song: "Fever", season:7, style:"Foxtrot", dancer_id:151 )
# Performance.create!(name:"Billy Bell" ,partner:"Robert Roldan" , song: "Ganesh", season:7, style:"Bollywood", dancer_id: 20 )
# Performance.create!(name:"Lauren Froderman" ,partner:"Pasha Kovalev" , song: "Oblivion", season:7, style:"Argentine Tango", dancer_id: 151)
# Performance.create!(name:"Lauren Gottlieb" ,partner:"AdéChiké Torbert " , song: "The Path", season:7, style:"African Jazz", dancer_id: 152 )
# Performance.create!(name:"Robert Roldan" ,partner:"Anya Garnis" , song: "Lost", season:7, style:"Viennese Waltz", dancer_id: )
# Performance.create!(name:"Kent Boyd" ,partner:"Courtney Galiano" , song: "When Love Takes Over", season:7, style:"Disco", dancer_id: 146 )
# Performance.create!(name:"Lauren Froderman" ,partner:"Ade Obayomi" , song: "Hide U", season:7, style:"Jazz", dancer_id: 151 )
# Performance.create!(name:"Kathryn McCormick" ,partner:"AdéChiké Torbert " , song: "Fearless Love", season:7, style:"Contemporary", dancer_id: 143 )
# Performance.create!(name:"Robert Roldan" ,partner:"Dominic Sandoval" , song: "Scars", season:7, style:"Hip-hop", dancer_id: 194 )
# Performance.create!(name:"Kent Boyd" ,partner:"Neil Haskell" , song: "How It Ends", season:7, style:"Contemporary", dancer_id:146 )
# Performance.create!(name:"Kent Boyd" ,partner:"Lauren Gottlieb" , song: "Om Mangalam", season:7, style:"Bollywood", dancer_id: 146)
# Performance.create!(name:"Twitch Boss" ,partner:"Lauren Froderman" , song: "Power", season:7, style:"Hip-hop", dancer_id: 206 )
# Performance.create!(name:"Mark Kanemura" ,partner:"Robert Roldan" , song: "Whip It", season:7, style:"Jazz", dancer_id: 156)
# Performance.create!(name:"Lauren Froderman" ,partner:"Robert Roldan" , song: "That Home", season:7, style:"Contemporary", dancer_id: 151 )
# Performance.create!(name:"Lauren Froderman" ,partner:"Kent Boyd" , song: "Hip to be Square", season:7, style:"Jazz", dancer_id: 151 )
# Performance.create!(name:"Allison Holker" ,partner:"Kent Boyd" , song: "Sundrenched World", season:7, style:"Contemporary", dancer_id: 10 )
# Performance.create!(name:"Kathryn McCormick" ,partner:"Robert Roldan" , song: "Cool", season:7, style:"Broadway", dancer_id: 143 )
# Performance.create!(name:"Lauren Froderman" ,partner:"Pasha Kovalev" , song: "Not Myself Tonight", season:7, style:"Cha-cha-cha", dancer_id: 151 )
# Performance.create!(name:"Kent Boyd" ,partner:"Robert Roldan" , song: "The Chosen/Drum Addict", season:7, style:"Malevos", dancer_id: 146 )



Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
Performance.create!(name:"" ,partner:"" , song: "", season:7, style:"", dancer_id: )
