Performance.create!(dancer_name:"Rayven Armijo" ,partner:"Jamie Bayard" , song: "American Boy", season:4, style:"Hip-Hop", dancer_id: 191 , partner_id: 69)
Performance.create!(dancer_name:"Susie Garcia" ,partner:"Marquis Cunningham" , song: "Dark Waltz", season:4, style:"Waltz", dancer_id: 198 , partner_id:158)
Performance.create!(dancer_name:"Kourtni Lind" ,partner:"Matt Dorame" , song: "Tainted Love", season:4, style:"Jazz", dancer_id:148 , partner_id:160)
Performance.create!(dancer_name:"Chelsea Traille" ,partner:"Thayne Jasperson" , song: "Oye Como Va", season:4, style:"Cha-cha-cha", dancer_id:38 , partner_id:200)
Performance.create!(dancer_name:"Chelsie Hightower" ,partner:"Mark Kanemura" , song: "Beautiful", season:4, style:"Contemporary", dancer_id:39 , partner_id:156)
Performance.create!(dancer_name:"Kherington Payne" ,partner:"Twitch Boss" , song: "Too Damn Hot", season:4, style:"Broadway", dancer_id:147 , partner_id: 206)
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Chris Jarosz" , song: "Boom Boom", season:4, style:"Jive", dancer_id: 44, partner_id:)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Joshua Allen" , song: "No Air", season:4, style:"Lyrical hip-hop", dancer_id: 142, partner_id:135)
Performance.create!(dancer_name:"Jessica King" ,partner:"William Wingfield" , song: "Tango", season:4, style:"Tango", dancer_id:128 , partner_id:211)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Gev Manoukian" , song: "Boogie Wonderland", season:4, style:"Disco", dancer_id:45 , partner_id:62)
Performance.create!(dancer_name:"Chelsea Traille" ,partner:"Thayne Jasperson" , song: "Untouched", season:4, style:"Jazz", dancer_id: 38 , partner_id:200)
Performance.create!(dancer_name:"Chelsie Hightower" ,partner:"Mark Kanemura" , song: "Mi Confesion", season:4, style:"Argentine Tango", dancer_id: 39 , partner_id: 156)
Performance.create!(dancer_name:"Jessica King" ,partner:"William Wingfield" , song: "Whatever U Like", season:4, style:"Hip-Hop", dancer_id:128 , partner_id:211)
Performance.create!(dancer_name:"Kourtni Lind" ,partner:"Matt Dorame" , song: "A Foggy Day (In London Town)", season:4, style:"Foxtrot", dancer_id:148 , partner_id:160)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Gev Manoukian" , song: "Lost", season:4, style:"Contemporary", dancer_id:45 , partner_id:62)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Joshua Allen" , song: "All for the Best", season:4, style:"Broadway", dancer_id:142 , partner_id:135)
Performance.create!(dancer_name:"Susie Garcia" ,partner:"Marquis Cunningham" , song: "Aguanile", season:4, style:"Salsa", dancer_id: 198, partner_id:158)
Performance.create!(dancer_name:"Kherington Payne" ,partner:"Twitch Boss" , song: "A New Day Has Come", season:4, style:"Viennese Waltz", dancer_id:147 , partner_id:206)
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Chris Jarosz" , song: "Come and Get Me", season:4, style:"Krump", dancer_id:44, partner_id:)
Performance.create!(dancer_name:"Kherington Payne" ,partner:"Twitch Boss" , song: "Don't Touch Me", season:4, style:"Hip-hop", dancer_id:147 , partner_id:206)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Gev Manoukian" , song: "Wishing on a Star", season:4, style:"Rumba", dancer_id:45 , partner_id:62)
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Chris Jarosz" , song: "The Beautiful People", season:4, style:"Afro Jazz", dancer_id:44 , partner_id:)
Performance.create!(dancer_name:"Jessica King" ,partner:"William Wingfield" , song: "Heaven Must Have Sent you", season:4, style:"Disco", dancer_id:128 , partner_id:211)
Performance.create!(dancer_name:"Kourtni Lind" ,partner:"Matt Dorame" , song: "Wrestlers", season:4, style:"Contemporary", dancer_id:148 , partner_id:160)
Performance.create!(dancer_name:"Chelsea Traille" ,partner:"Thayne Jasperson" , song: "You Can't Hurry Love", season:4, style:"Quickstep", dancer_id:38 , partner_id:200)
Performance.create!(dancer_name:"Chelsie Hightower" ,partner:"Mark Kanemura" , song: "Bleeding Love", season:4, style:"Lyrical Hip-hop", dancer_id: 39 , partner_id: 156)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Joshua Allen" , song: "Baila, Baila", season:4, style:"Samba", dancer_id:142 , partner_id:135)
Performance.create!(dancer_name:"Jessica King" ,partner:"William Wingfield" , song: "Choo Choo Ch'Boogie", season:4, style:"Jive", dancer_id: 128 , partner_id:211)
Performance.create!(dancer_name:"Jessica King" ,partner:"William Wingfield" , song: "Alone", season:4, style:"Lyrical Jazz", dancer_id:128 , partner_id:211)
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Thayne Jasperson" , song: "Cool", season:4, style:"Broadway", dancer_id:44 , partner_id:200)
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Thayne Jasperson" , song: "Hov Arek Sarer Jan", season:4, style:"Smooth Waltz", dancer_id:44 , partner_id:200)
Performance.create!(dancer_name:"Kourtni Lind" ,partner:"Matt Dorame" , song: "How Do I Breathe", season:4, style:"Hip-hop", dancer_id:148 , partner_id:160)
Performance.create!(dancer_name:"Kourtni Lind" ,partner:"Matt Dorame" , song: "Ban Com Tim", season:4, style:"Mambo", dancer_id:148 , partner_id:160)
Performance.create!(dancer_name:"Chelsie Hightower" ,partner:"Mark Kanemura" , song: "Kiss Kiss", season:4, style:"Jazz", dancer_id: 39 , partner_id: 156)
Performance.create!(dancer_name:"Chelsie Hightower" ,partner:"Mark Kanemura" , song: "It's my Life", season:4, style:"Foxtrot", dancer_id: 39 , partner_id: 156)
Performance.create!(dancer_name:"Kherington Payne" ,partner:"Twitch Boss" , song: "Malaguena", season:4, style:"Paso Doble", dancer_id:147 , partner_id:206)
Performance.create!(dancer_name:"Kherington Payne" ,partner:"Twitch Boss" , song: "Dreaming with a Broken Heart", season:4, style:"Contemporary", dancer_id:147 , partner_id: 206)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Joshua Allen" , song: "Hometown Glory", season:4, style:"Contemporary", dancer_id:142 , partner_id:135)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Joshua Allen" , song: "Shake it", season:4, style:"West Coast Swing", dancer_id: 142, partner_id:135)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Gev Manoukian" , song: "Lights, Camera, Action!", season:4, style:"Hip-hop", dancer_id:45 , partner_id:62)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Gev Manoukian" , song: "New York, New York", season:4, style:"Broadway", dancer_id:45 , partner_id:62)
Performance.create!(dancer_name:"Chelsie Hightower" ,partner:"Mark Kanemura" , song: "Fuego", season:4, style:"Salsa", dancer_id: 39 , partner_id: 156)
Performance.create!(dancer_name:"Mark Kanemura" ,partner:"Chelsie Hightower" , song: "I'm a Woman", season:4, style:"Broadway", dancer_id:156 , partner_id: 39)
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Thayne Jasperson" , song: "Can We Chill", season:4, style:"Hip-hop", dancer_id: 44, partner_id:200)
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Thayne Jasperson" , song: "A Different Corner", season:4, style:"Contemporary", dancer_id:44 , partner_id:200)
Performance.create!(dancer_name:"Jessica King" ,partner:"William Wingfield" , song: "Silence", season:4, style:"Contemporary", dancer_id:128 , partner_id:211)
Performance.create!(dancer_name:"William Wingfield" ,partner:"Jessica King" , song: "Bandstand Boogie", season:4, style:"Quickstep", dancer_id:211 , partner_id:128)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Gev Manoukian" , song: "Don't stop the Music", season:4, style:"Cha-cha-cha", dancer_id:45 , partner_id:62)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Gev Manoukian" , song: "Standing There", season:4, style:"Jazz", dancer_id: 45 , partner_id:62)
Performance.create!(dancer_name:"Kherington Payne" ,partner:"Twitch Boss" , song: "2 Buck 4 TV", season:4, style:"Krump", dancer_id:147 , partner_id: 206)
Performance.create!(dancer_name:"Kherington Payne" ,partner:"Twitch Boss" , song: "Assassin's Tango", season:4, style:"Tango", dancer_id:147 , partner_id: 206)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Joshua Allen" , song: "Iris", season:4, style:"Vienesse Waltz", dancer_id:142 , partner_id:135)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Joshua Allen" , song: "Dhoom Taana", season:4, style:"Bollywood", dancer_id:142 , partner_id:135)
Performance.create!(dancer_name:"Courtney Gailiano" ,partner:"Joshua Allen" , song: "Skippin", season:4, style:"Hip-hop", dancer_id:45 , partner_id:135)
Performance.create!(dancer_name:"Courtney Gailiano" ,partner:"Joshua Allen" , song: "Hero", season:4, style:"Rumba", dancer_id:45 , partner_id:135)
Performance.create!(dancer_name:"Kherington Payne" ,partner:"Mark Kanemura" , song: "Kick Back", season:4, style:"Country-western two step", dancer_id:147 , partner_id: 156)
Performance.create!(dancer_name:"Mark Kanemura" ,partner:"Kherington Payne" , song: "Canned Heat", season:4, style:"Jazz", dancer_id: 156 , partner_id:147)
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Twitch Boss" , song: "Open Arms", season:4, style:"Smooth Waltz", dancer_id:44 , partner_id:206)
Performance.create!(dancer_name:"Twitch Boss" ,partner:"Comfort Fedoke" , song: "Forever", season:4, style:"Hip-hop", dancer_id: 206, partner_id:44)
Performance.create!(dancer_name:"Katee Shean" ,partner:"William Wingfield" , song: "Sit Down You're Rocking the Boat", season:4, style:"Broadway", dancer_id:142 , partner_id:211)
Performance.create!(dancer_name:"Katee Shean" ,partner:"William Wingfield" , song: "Imagine", season:4, style:"Pas de deux", dancer_id: 142, partner_id:211)
Performance.create!(dancer_name:"Chelsie Hightower" ,partner:"Gev Manoukian" , song: "The House is Rockin", season:4, style:"Jive", dancer_id: 39 , partner_id:62)
Performance.create!(dancer_name:"Gev Manoukian" ,partner:"Chelsie Hightower" , song: "These Arms of Mine", season:4, style:"Contemporary", dancer_id: 62, partner_id: 39)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"William Wingfield" , song: "I  Fell in Love with a DJ", season:4, style:"Samba", dancer_id:45 , partner_id:)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"William Wingfield" , song: "Like You'll Never See Me Again", season:4, style:"Lyrical Hip-hop", dancer_id:45 , partner_id:)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Twitch Boss" , song: "Mercy", season:4, style:"Contemporary", dancer_id:142 , partner_id: 206)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Twitch Boss" , song: "Sweet Georgia Brown", season:4, style:"Broadway", dancer_id:142 , partner_id: 206)
Performance.create!(dancer_name:"Comfort Fedoke" ,partner:"Mark Kanemura" , song: "Party People", season:4, style:"Hip-hop", dancer_id:44 , partner_id: 156)
Performance.create!(dancer_name:"Mark Kanemura" ,partner:"Comfort Fedoke" , song: "Lady Luck", season:4, style:"Foxtrot", dancer_id: 156 , partner_id:44)
Performance.create!(dancer_name:"Joshua Allen" ,partner:"Chelsie Hightower" , song: "A Los Amigos", season:4, style:"Argentine Tango", dancer_id: 39, partner_id: 135)
Performance.create!(dancer_name:"Chelsie Hightower" ,partner:"Joshua Allen" , song: "Everlasting Love", season:4, style:"Disco", dancer_id: 39 , partner_id:135)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Mark Kanemura" , song: "The Time of My Life", season:4, style:"Viennese Waltz", dancer_id:45 , partner_id: 156)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Mark Kanemura" , song: "The Garden", season:4, style:"Jazz", dancer_id:45 , partner_id: 156)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Joshua Allen" , song: "All By Myself", season:4, style:"Contemporary", dancer_id:142 , partner_id:135)
Performance.create!(dancer_name:"Joshua Allen" ,partner:"Katee Shean" , song: "Filet", season:4, style:"Paso Doble", dancer_id:135 , partner_id:)
Performance.create!(dancer_name:"Chelsie Hightower" ,partner:"Twitch Boss" , song: "Ahora Me Toca a Mi", season:4, style:"Mambo", dancer_id: 39, partner_id: 206)
Performance.create!(dancer_name:"Twitch Boss" ,partner:"Chelsie Hightower" , song: "Control", season:4, style:"Hip-hop", dancer_id: 206 , partner_id:39)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Twitch Boss" , song: "Church", season:4, style:"Hip-hop", dancer_id:45 , partner_id:)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Joshua Allen" , song: "Slow Dancing in a Burning Room", season:4, style:"Lyrical Jazz", dancer_id:142 , partner_id:135)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Katee Shean" , song: "The Trolley Song", season:4, style:"Broadway", dancer_id: 45, partner_id:142)
Performance.create!(dancer_name:"Joshua Allen" ,partner:"Twitch Boss" , song: "Trepak", season:4, style:"Trepak", dancer_id:135 , partner_id: 206)
Performance.create!(dancer_name:"Katee Shean" ,partner:"Twitch Boss" , song: "Feeling Good", season:4, style:"Foxtrot", dancer_id:142 , partner_id: 206)
Performance.create!(dancer_name:"Courtney Galiano" ,partner:"Joshua Allen" , song: "The Dirty Boogie", season:4, style:"Jive", dancer_id:45 , partner_id:135)
# Performance.create!(dancer_name:"" ,partner:"" , song: "", season:4, style:"", dancer_id: , partner_id:)
# Performance.create!(dancer_name:"" ,partner:"" , song: "", season:4, style:"", dancer_id: , partner_id:)
# Performance.create!(dancer_name:"" ,partner:"" , song: "", season:4, style:"", dancer_id: , partner_id:)
# Performance.create!(dancer_name:"" ,partner:"" , song: "", season:4, style:"", dancer_id: , partner_id:)
# Performance.create!(dancer_name:"" ,partner:"" , song: "", season:4, style:"", dancer_id: , partner_id:)
# Performance.create!(dancer_name:"" ,partner:"" , song: "", season:4, style:"", dancer_id: , partner_id:)
# Performance.create!(dancer_name:"" ,partner:"" , song: "", season:4, style:"", dancer_id: , partner_id:)
# Performance.create!(dancer_name:"" ,partner:"" , song: "", season:4, style:"", dancer_id: )
# Performance.create!(dancer_name:"" ,partner:"" , song: "", season:4, style:"", dancer_id: )
