Dancer.create!([
  {full_name: "Adéchiké Torbert", first_name: "Adéchiké\n", last_name: "Torbert"},
  {full_name: "Alex Wong", first_name: "Alex\n", last_name: "Wong"},
  {full_name: "Alexa Anderson", first_name: "Alexa\n", last_name: "Anderson"},
  {full_name: "Alexander Fost", first_name: "Alexander\n", last_name: "Fost"},
  {full_name: "Alexie Agdeppa", first_name: "Alexie\n", last_name: "Agdeppa"},
  {full_name: "Allan Frias", first_name: "Allan\n", last_name: "Frias"},
  {full_name: "Amber Jackson", first_name: "Amber\n", last_name: "Jackson"},
  {full_name: "Amelia Lowe", first_name: "Amelia\n", last_name: "Lowe"},
  {full_name: "Anya Garnis", first_name: "Anya\n", last_name: "Garnis"},
  {full_name: "Artem Chigvinsev", first_name: "Artem\n", last_name: "Chigvinsev"},
  {full_name: "Ashle Dawson", first_name: "Ashle\n", last_name: "Dawson"},
  {full_name: "Ashlee Nino", first_name: "Ashlee\n", last_name: "Nino"},
  {full_name: "Ashleigh DiLello", first_name: "Ashleigh\n", last_name: "DiLello"},
  {full_name: "Ashley Galvan", first_name: "Ashley\n", last_name: "Galvan"},
  {full_name: "Ashley Rich", first_name: "Ashley\n", last_name: "Rich"},
  {full_name: "Asuka Kondoh", first_name: "Asuka\n", last_name: "Kondoh"},
  {full_name: "Audrey Case", first_name: "Audrey\n", last_name: "Case"},
  {full_name: "Ben Susak", first_name: "Ben\n", last_name: "Susak"},
  {full_name: "Benji Schwimmer", first_name: "Benji\n", last_name: "Schwimmer"},
  {full_name: "Bianca Revels", first_name: "Bianca\n", last_name: "Revels"},
  {full_name: "Billy Bell", first_name: "Billy\n", last_name: "Bell"},
  {full_name: "Brandon Bryant", first_name: "Brandon\n", last_name: "Bryant"},
  {full_name: "Brandon Mitchell", first_name: "Brandon\n", last_name: "Mitchell"},
  {full_name: "Caitlynn Lawson", first_name: "Caitlynn\n", last_name: "Lawson"},
  {full_name: "Cedric Gardner", first_name: "Cedric\n", last_name: "Gardner"},
  {full_name: "Chehon Wespi-Tschopp", first_name: "Chehon\n", last_name: "Wespi-Tschopp"},
  {full_name: "Chelsea Traille", first_name: "Chelsea\n", last_name: "Traille"},
  {full_name: "Chris Jarosz", first_name: "Chris\n", last_name: "Jarosz"},
  {full_name: "Chris Koehl", first_name: "Chris\n", last_name: "Koehl"},
  {full_name: "Clarice Ordaz", first_name: "Clarice\n", last_name: "Ordaz"},
  {full_name: "Cole Horibe", first_name: "Cole\n", last_name: "Horibe"},
  {full_name: "Courtney Galiano", first_name: "Courtney\n", last_name: "Galiano"},
  {full_name: "Craig DeRosa", first_name: "Craig\n", last_name: "DeRosa"},
  {full_name: "Cyrus Spencer", first_name: "Cyrus\n", last_name: "Spencer"},
  {full_name: "Daniel Baker", first_name: "Daniel\n", last_name: "Baker"},
  {full_name: "Danny Tidwell", first_name: "Danny\n", last_name: "Tidwell"},
  {full_name: "Dareian Kujawa", first_name: "Dareian\n", last_name: "Kujawa"},
  {full_name: "Dmitry Chaplin", first_name: "Dmitry\n", last_name: "Chaplin"},
  {full_name: "Dominic Sandoval", first_name: "Dominic\n", last_name: "Sandoval"},
  {full_name: "Donyelle Jones", first_name: "Donyelle\n", last_name: "Jones"},
  {full_name: "Ellenore Scott", first_name: "Ellenore\n", last_name: "Scott"},
  {full_name: "Erin Ellis", first_name: "Erin\n", last_name: "Ellis"},
  {full_name: "Evan Kasprzak", first_name: "Evan\n", last_name: "Kasprzak"},
  {full_name: "George Lawrence Jr.", first_name: "George\n", last_name: "Lawrence"},
  {full_name: "Gev Manoukian", first_name: "Gev\n", last_name: "Manoukian"},
  {full_name: "Heidi Groskreutz", first_name: "Heidi\n", last_name: "Groskreutz"},
  {full_name: "Ivan Koumaev", first_name: "Ivan\n", last_name: "Koumaev"},
  {full_name: "Iveta Lukosiute", first_name: "Iveta\n", last_name: "Lukosiute"},
  {full_name: "Jakob Karr", first_name: "Jakob\n", last_name: "Karr"},
  {full_name: "Jamie Bayard", first_name: "Jamie\n", last_name: "Bayard"},
  {full_name: "Jamile McGee", first_name: "Jamile\n", last_name: "McGee"},
  {full_name: "Janelle Issis", first_name: "Janelle\n", last_name: "Issis"},
  {full_name: "Janette Manrara", first_name: "Janette\n", last_name: "Manrara"},
  {full_name: "Jason Glover", first_name: "Jason\n", last_name: "Glover"},
  {full_name: "Jaymz Tuaileva", first_name: "Jaymz\n", last_name: "Tuaileva"},
  {full_name: "Jeanine Mason", first_name: "Jeanine\n", last_name: "Mason"},
  {full_name: "Adam Cooper", first_name: "Adam\n", last_name: "Cooper"},
  {full_name: "Ade Obayomi", first_name: "Ade\n", last_name: "Obayomi"},
  {full_name: "Aleksandra Wojda", first_name: "Aleksandra\n", last_name: "Wojda"},
  {full_name: "Allison Holker", first_name: "Allison\n", last_name: "Holker"},
  {full_name: "Ariana DeBose", first_name: "Ariana\n", last_name: "DeBose"},
  {full_name: "Ashlee Langas", first_name: "Ashlee\n", last_name: "Langas"},
  {full_name: "Ashley Valerio", first_name: "Ashley\n", last_name: "Valerio"},
  {full_name: "Barry Adelman", first_name: "Barry\n", last_name: "Adelman"},
  {full_name: "Blake McGrath", first_name: "Blake\n", last_name: "McGrath"},
  {full_name: "Caitlin Kinney", first_name: "Caitlin\n", last_name: "Kinney"},
  {full_name: "Channing Cooke", first_name: "Channing\n", last_name: "Cooke"},
  {full_name: "Chelsie Hightower", first_name: "Chelsie\n", last_name: "Hightower"},
  {full_name: "Comfort Fedoke", first_name: "Comfort\n", last_name: "Fedoke"},
  {full_name: "Cristina Santana", first_name: "Cristina\n", last_name: "Santana"},
  {full_name: "Destini Rogers", first_name: "Destini\n", last_name: "Rogers"},
  {full_name: "Eliana Girard", first_name: "Eliana\n", last_name: "Girard"},
  {full_name: "Faina Savich", first_name: "Faina\n", last_name: "Savich"},
  {full_name: "Hok Konishi", first_name: "Hok\n", last_name: "Konishi"},
  {full_name: "Jaimie Goodwin", first_name: "Jaimie\n", last_name: "Goodwin"},
  {full_name: "Janaya French", first_name: "Janaya\n", last_name: "French"},
  {full_name: "Jason Williams", first_name: "Jason\n", last_name: "Williams"},
  {full_name: "Jess LeProtto\n", first_name: "Jess\n", last_name: "LeProtto"},
  {full_name: "Jessica Fernandez", first_name: "Jessica\n", last_name: "Fernandez"},
  {full_name: "Jessica King", first_name: "Jessica\n", last_name: "King"},
  {full_name: "Jesus Solorio", first_name: "Jesus\n", last_name: "Solorio"},
  {full_name: "Jonathan Platero", first_name: "Jonathan\n", last_name: "Platero"},
  {full_name: "Jonnis Tannis", first_name: "Jonnis\n", last_name: "Tannis"},
  {full_name: "Jose Ruiz", first_name: "Jose\n", last_name: "Ruiz"},
  {full_name: "Joshua Allen", first_name: "Joshua\n", last_name: "Allen"},
  {full_name: "Joy Spears", first_name: "Joy\n", last_name: "Spears"},
  {full_name: "K'Bez Hunte", first_name: "K'Bez\n", last_name: "Hunte"},
  {full_name: "Kamilah Barrett", first_name: "Kamilah\n", last_name: "Barrett"},
  {full_name: "Karen Hauer", first_name: "Karen\n", last_name: "Hauer"},
  {full_name: "Katee Shean", first_name: "Katee\n", last_name: "Shean"},
  {full_name: "Kathryn McCormick", first_name: "Kathryn\n", last_name: "McCormick"},
  {full_name: "Kayla Radomski", first_name: "Kayla\n", last_name: "Radomski"},
  {full_name: "Kent Boyd", first_name: "Kent\n", last_name: "Boyd"},
  {full_name: "Kherington Payne", first_name: "Kherington\n", last_name: "Payne"},
  {full_name: "Kourtni Lind", first_name: "Kourtni\n", last_name: "Lind"},
  {full_name: "Lacey Schwimmer", first_name: "Lacey\n", last_name: "Schwimmer"},
  {full_name: "Lauren Froderman", first_name: "Lauren\n", last_name: "Froderman"},
  {full_name: "Lauren Sanchez", first_name: "Lauren\n", last_name: "Sanchez"},
  {full_name: "Legacy Perez", first_name: "Legacy\n", last_name: "Perez"},
  {full_name: "Lindsay Arnold", first_name: "Lindsay\n", last_name: "Arnold"},
  {full_name: "Mark Kanemura", first_name: "Mark\n", last_name: "Kanemura"},
  {full_name: "Marquis Cunningham", first_name: "Marquis\n", last_name: "Cunningham"},
  {full_name: "Martha Nichols", first_name: "Martha\n", last_name: "Nichols"},
  {full_name: "Matt Dorame", first_name: "Matt\n", last_name: "Dorame"},
  {full_name: "Matthew Kazmierczak", first_name: "Matthew\n", last_name: "Kazmierczak"},
  {full_name: "Max Kapitannikov", first_name: "Max\n", last_name: "Kapitannikov"},
  {full_name: "Melinda Sullivan", first_name: "Melinda\n", last_name: "Sullivan"},
  {full_name: "Melissa Sandvig", first_name: "Melissa\n", last_name: "Sandvig"},
  {full_name: "Melody Lacayanga", first_name: "Melody\n", last_name: "Lacayanga"},
  {full_name: "Michael Mead", first_name: "Michael\n", last_name: "Mead"},
  {full_name: "Mike Deffina", first_name: "Mike\n", last_name: "Deffina"},
  {full_name: "Miranda Maleski", first_name: "Miranda\n", last_name: "Maleski"},
  {full_name: "Missy Morelli", first_name: "Missy\n", last_name: "Morelli"},
  {full_name: "Mollee Gray", first_name: "Mollee\n", last_name: "Gray"},
  {full_name: "Natalie Fotopoulos", first_name: "Natalie\n", last_name: "Fotopoulos"},
  {full_name: "Nathan Trasoras", first_name: "Nathan\n", last_name: "Trasoras"},
  {full_name: "Nick Bloxsom-Carter", first_name: "Nick\n", last_name: "Bloxsom-Carter"},
  {full_name: "Nick Lazzarini", first_name: "Nick\n", last_name: "Lazzarini"},
  {full_name: "Nick Young", first_name: "Nick\n", last_name: "Young"},
  {full_name: "Paris Torres", first_name: "Paris\n", last_name: "Torres"},
  {full_name: "Pasha Kovalev", first_name: "Pasha\n", last_name: "Kovalev"},
  {full_name: "Peter Sabasino", first_name: "Peter\n", last_name: "Sabasino"},
  {full_name: "Phillip Attmore", first_name: "Phillip\n", last_name: "Attmore"},
  {full_name: "Phillip Chbeeb", first_name: "Phillip\n", last_name: "Chbeeb"},
  {full_name: "Pia Toscano", first_name: "Pia\n", last_name: "Toscano"},
  {full_name: "Rayven Armijo", first_name: "Rayven\n", last_name: "Armijo"},
  {full_name: "Ricky Jaime", first_name: "Ricky\n", last_name: "Jaime"},
  {full_name: "Robert Roldan", first_name: "Robert\n", last_name: "Roldan"},
  {full_name: "Robert Taylor Jr.", first_name: "Robert\n", last_name: "Taylor"},
  {full_name: "Ron Montez", first_name: "Ron\n", last_name: "Montez"},
  {full_name: "Susie Garcia", first_name: "Susie\n", last_name: "Garcia"},
  {full_name: "Tadd Gadduang", first_name: "Tadd\n", last_name: "Gadduang"},
  {full_name: "Thayne Jasperson", first_name: "Thayne\n", last_name: "Jasperson"},
  {full_name: "Toni Basil", first_name: "Toni\n", last_name: "Basil"},
  {full_name: "Toni Redpath", first_name: "Toni\n", last_name: "Redpath"},
  {full_name: "Tony Bellissimo", first_name: "Tony\n", last_name: "Bellissimo"},
  {full_name: "Travis Wall", first_name: "Travis\n", last_name: "Wall"},
  {full_name: "Victor Smalley", first_name: "Victor\n", last_name: "Smalley"},
  {full_name: "Vitolio Jeune", first_name: "Vitolio\n", last_name: "Jeune"},
  {full_name: "Will Thomas", first_name: "Will\n", last_name: "Thomas"},
  {full_name: "Will Wingfield", first_name: "Will\n", last_name: "Wingfield"},
  {full_name: "Witney Carson", first_name: "Witney\n", last_name: "Carson"},
  {full_name: "Jessi Peralta", first_name: "Jessi\n", last_name: "Peralta"},
  {full_name: "Jimmy Arguello", first_name: "Jimmy\n", last_name: "Arguello"},
  {full_name: "Jordan Casanova", first_name: "Jordan\n", last_name: "Casanova"},
  {full_name: "Kameron Bink", first_name: "Kameron\n", last_name: "Bink"},
  {full_name: "Karla Garcia", first_name: "Karla\n", last_name: "Garcia"},
  {full_name: "Kenny Ortega", first_name: "Kenny\n", last_name: "Ortega"},
  {full_name: "Kupono Aweau", first_name: "Kupono\n", last_name: "Aweau"},
  {full_name: "Lauren Gottlieb", first_name: "Lauren\n", last_name: "Gottlieb"},
  {full_name: "Marko Germar", first_name: "Marko\n", last_name: "Germar"},
  {full_name: "Matthew Diamond", first_name: "Matthew\n", last_name: "Diamond"},
  {full_name: "Melanie Moore", first_name: "Melanie\n", last_name: "Moore"},
  {full_name: "Melissa Vella", first_name: "Melissa\n", last_name: "Vella"},
  {full_name: "Michelle Brooke", first_name: "Michelle\n", last_name: "Brooke"},
  {full_name: "Musa Cooper", first_name: "Musa\n", last_name: "Cooper"},
  {full_name: "Neil Haskell", first_name: "Neil\n", last_name: "Haskell"},
  {full_name: "Noelle Marsh", first_name: "Noelle\n", last_name: "Marsh"},
  {full_name: "Pauline Mata", first_name: "Pauline\n", last_name: "Mata"},
  {full_name: "Randi Evans", first_name: "Randi\n", last_name: "Evans"},
  {full_name: "Ricky Palamino", first_name: "Ricky\n", last_name: "Palamino"},
  {full_name: "Stanislav Savich", first_name: "Stanislav\n", last_name: "Savich"},
  {full_name: "Tiffany Maher", first_name: "Tiffany\n", last_name: "Maher"},
  {full_name: "Twitch Boss", first_name: "Twitch\n", last_name: "Boss"},
  {full_name: "Wadi Jones", first_name: "Wadi\n", last_name: "Jones"}
])
Performance.create!([
  {dancer_name: "Billy Bell", partner: "Lauren Gottileb", song: "Footloose", season: 7, style: "Broadway", dancer_id: 29, url: nil, video_id: nil, partner_id: 152},
  {dancer_name: "Comfort Fedoke", partner: "Jose Ruiz", song: "Beautiful Monster", season: 7, style: "Hip-Hop", dancer_id: 44, url: nil, video_id: nil, partner_id: 134},
  {dancer_name: "Kathryn McCormick", partner: "AdéChiké Torbert ", song: " Addicted to Love", season: 7, style: "Jazz", dancer_id: 96, url: nil, video_id: nil, partner_id: 3},
  {dancer_name: "Pasha Kovalev", partner: "Melinda Sullivan ", song: "L-O-V-E", season: 7, style: "Jive", dancer_id: 138, url: nil, video_id: nil, partner_id: 165},
  {dancer_name: "Allison Holker", partner: "Alex Wong", song: "Hallelujah", season: 7, style: "Contemporary", dancer_id: 10, url: nil, video_id: nil, partner_id: 5},
  {dancer_name: "Alexie Agdeppa", partner: "Twitch Boss", song: "Butterfly", season: 7, style: "Hip-Hop", dancer_id: 8, url: nil, video_id: nil, partner_id: 206},
  {dancer_name: "Lauren Froderman", partner: "Ade Obayomi", song: "Oh Yeah", season: 7, style: "Pop-Jazz", dancer_id: 151, url: nil, video_id: nil, partner_id: 2},
  {dancer_name: "Kent Boyd", partner: "Anya Garnis", song: "Lady Marmalade", season: 7, style: "Cha-cha=cha", dancer_id: 146, url: nil, video_id: nil, partner_id: 13},
  {dancer_name: "Ashley Galvan", partner: "Neil Haskell", song: "For All We Know", season: 7, style: "Contemporary", dancer_id: 20, url: nil, video_id: nil, partner_id: 178},
  {dancer_name: "Courtney Galiano", partner: "Robert Roldan", song: "Norweg", season: 7, style: "African Jazz", dancer_id: 45, url: nil, video_id: nil, partner_id: 194},
  {dancer_name: "Pasha Kovalev", partner: "Christina Santana", song: "Ira Deorum/Sanctus", season: 7, style: "Paso Doble", dancer_id: 138, url: nil, video_id: nil, partner_id: nil},
  {dancer_name: "Allison Holker", partner: "AdéChiké Torbert", song: "Listen to Your Heart", season: 7, style: "Contemporary", dancer_id: 10, url: nil, video_id: nil, partner_id: 3},
  {dancer_name: "Lauren Gottlieb", partner: "Alex Wong", song: "Summertime", season: 7, style: "Broadway", dancer_id: 152, url: nil, video_id: nil, partner_id: 194},
  {dancer_name: "Kathryn McCormick", partner: "Jose Ruiz", song: "Marjaani Marjaani Kasama", season: 7, style: "Bollywood", dancer_id: 96, url: nil, video_id: nil, partner_id: 134},
  {dancer_name: "Kent Boyd", partner: "Courtney Gailiano", song: "Amy Amy Amy", season: 7, style: "Jazz", dancer_id: 146, url: nil, video_id: nil, partner_id: 45},
  {dancer_name: "Lauren Gottlieb", partner: "AdéChiké Torbert ", song: "Hot-N-Fun", season: 7, style: "Hip-Hop", dancer_id: 152, url: nil, video_id: nil, partner_id: 3},
  {dancer_name: "Lauren Gottlieb", partner: "AdéChiké Torbert ", song: "Hot-N-Fun", season: 7, style: "Hip-Hop", dancer_id: 152, url: nil, video_id: nil, partner_id: 3},
  {dancer_name: "Ashley Galvan", partner: "Ade Obayomi", song: "Cosmic Love", season: 7, style: "Contemporary", dancer_id: 20, url: nil, video_id: nil, partner_id: 2},
  {dancer_name: "Courtney Galiano", partner: "Robert Roldan", song: "XXXO", season: 7, style: "Jazz", dancer_id: 45, url: nil, video_id: nil, partner_id: 194},
  {dancer_name: "Pasha Kovalev", partner: "Melinda Sullivan", song: "Magdelena, Mi Amor", season: 7, style: "Salsa", dancer_id: 138, url: nil, video_id: nil, partner_id: 165},
  {dancer_name: "Lauren Froderman", partner: "Neil Haskell", song: "Let me Entertain You", season: 7, style: "Broadway", dancer_id: 151, url: nil, video_id: nil, partner_id: 178},
  {dancer_name: "Billy Bell", partner: "Kathryn McCormick", song: "Jar of Hearts", season: 7, style: "Contemporary", dancer_id: 29, url: nil, video_id: nil, partner_id: 143},
  {dancer_name: "Kent Boyd", partner: "Allison Holker", song: "Heartburn", season: 7, style: "Jazz", dancer_id: 146, url: nil, video_id: nil, partner_id: 10},
  {dancer_name: "Alex Wong", partner: "Twitch Boss", song: "Hip-Hop", season: 7, style: "Hip-Hop", dancer_id: 5, url: nil, video_id: nil, partner_id: 206},
  {dancer_name: "Lauren Froderman", partner: "Pasha Kovalev", song: "Telephone", season: 7, style: "Cha-cha-cha", dancer_id: 151, url: nil, video_id: nil, partner_id: 138},
  {dancer_name: "Lauren Gottileb", partner: "Jose Ruiz", song: "Never Tear us Apart", season: 7, style: "Contemporary", dancer_id: 152, url: nil, video_id: nil, partner_id: 134},
  {dancer_name: "Kent Boyd", partner: "Comfort Fedoke", song: "You're not my Girl", season: 7, style: "Hip-hop", dancer_id: 146, url: nil, video_id: nil, partner_id: 44},
  {dancer_name: "Courtney Galiano", partner: "AdéChiké Torbert  ", song: "Is You or is You Ain't my Baby", season: 7, style: "Jazz", dancer_id: 45, url: nil, video_id: nil, partner_id: 3},
  {dancer_name: "Billy Bell", partner: "Katee Shean", song: "Broadway", season: 7, style: "Broadway", dancer_id: 29, url: nil, video_id: nil, partner_id: 142},
  {dancer_name: "Ashley Galvan", partner: "Dominic Sandoval", song: "How Low", season: 7, style: "Hip-hop", dancer_id: 20, url: nil, video_id: nil, partner_id: 54},
  {dancer_name: "Kathyrn McCormick", partner: "Robert Roldan", song: "Sinking Feeling", season: 7, style: "Jazz", dancer_id: 143, url: nil, video_id: nil, partner_id: 194},
  {dancer_name: "AdéChiké Torbert  ", partner: "Maria", song: "Mourya Re", season: 7, style: "Bollywood", dancer_id: 3, url: nil, video_id: nil, partner_id: nil},
  {dancer_name: "Kent Boyd", partner: "Lauren Froderman", song: "Collide", season: 7, style: "Contemporary", dancer_id: 146, url: nil, video_id: nil, partner_id: 151},
  {dancer_name: "Ashely Galvan", partner: "Robert Roldan", song: "Man with the Hex", season: 7, style: "Quickstep", dancer_id: 20, url: nil, video_id: nil, partner_id: 194},
  {dancer_name: "Billy Bell", partner: "Jose Ruiz", song: "The Hunt", season: 7, style: "African Jazz", dancer_id: 29, url: nil, video_id: nil, partner_id: 134},
  {dancer_name: "Lauren Foderman", partner: "Mark Kanemura", song: "Jungle", season: 7, style: "Tahitan", dancer_id: 151, url: nil, video_id: nil, partner_id: 156},
  {dancer_name: "Anya Garnis", partner: "AdéChiké Torbert ", song: "Oyelo Que Te Convience", season: 7, style: "Salsa", dancer_id: 13, url: nil, video_id: nil, partner_id: 3},
  {dancer_name: "Allison Holker", partner: "Robert Roldan", song: "Fix you", season: 7, style: "Contemporary", dancer_id: 10, url: nil, video_id: nil, partner_id: 194},
  {dancer_name: "Billy Bell", partner: "Anya Garnis", song: "Paradise by the Dashboard Light", season: 7, style: "Jive", dancer_id: 20, url: nil, video_id: nil, partner_id: 13},
  {dancer_name: "Billy Bell", partner: "Lauren Froderman", song: "Boogie Shoes", season: 7, style: "Jazz", dancer_id: 20, url: nil, video_id: nil, partner_id: 151},
  {dancer_name: "Jose Ruiz", partner: "Dominic Sandoval", song: "Battle for the Beat", season: 7, style: "B-Boying", dancer_id: 134, url: nil, video_id: nil, partner_id: 134},
  {dancer_name: "Robert an", partner: "Kathyrn McCormick", song: "Instant Replay", season: 7, style: "Disco", dancer_id: 194, url: nil, video_id: nil, partner_id: 143},
  {dancer_name: "Twitch Boss", partner: "Lauren Froderman", song: "My Chick Bad", season: 7, style: "Hip-hop", dancer_id: 206, url: nil, video_id: nil, partner_id: 151},
  {dancer_name: "Allison Holker", partner: "Jose Ruiz", song: "Eternal Sunshine of the Mind theme", season: 7, style: "Contemporary", dancer_id: 10, url: nil, video_id: nil, partner_id: 134},
  {dancer_name: "Lauren Gottileb", partner: "Robert Roldan", song: "Wasted Time", season: 7, style: "Jazz", dancer_id: 152, url: nil, video_id: nil, partner_id: 194},
  {dancer_name: "Kent Boyd", partner: "Kathryn McCormick", song: "Tightrope", season: 7, style: "Jazz", dancer_id: 146, url: nil, video_id: nil, partner_id: 143},
  {dancer_name: "Comfort Fedoke", partner: "AdéChiké Torbert  ", song: "Fallin", season: 7, style: "Lyrical Hip-hop", dancer_id: 44, url: nil, video_id: nil, partner_id: 3},
  {dancer_name: "Jose Ruiz", partner: "AdéChiké Torbert ", song: "The Arrival", season: 7, style: "Paso Doble", dancer_id: 134, url: nil, video_id: nil, partner_id: 3},
  {dancer_name: "Kent Boyd", partner: "Twitch Boss", song: "Pro Nails", season: 7, style: "Stepping", dancer_id: 146, url: nil, video_id: nil, partner_id: 206},
  {dancer_name: "Kent Boyd", partner: "Anya Garnis", song: "My First Kiss", season: 7, style: "Cha-cha-cha", dancer_id: 146, url: nil, video_id: nil, partner_id: 13},
  {dancer_name: "Robert Roldan", partner: "Kathryn McCormick", song: "Heaven is a Place on Earth", season: 7, style: "Contemporary", dancer_id: 194, url: nil, video_id: nil, partner_id: 143},
  {dancer_name: "Courtney Galiliano", partner: "AdéChiké Torbert  ", song: "Manteca", season: 7, style: "Jazz", dancer_id: 45, url: nil, video_id: nil, partner_id: 3},
  {dancer_name: "Comfort Fedoke", partner: "Jose Ruiz", song: "Try a Little Tenderness", season: 7, style: "Hip-hop", dancer_id: 44, url: nil, video_id: nil, partner_id: 134},
  {dancer_name: "Billy Bell", partner: "Ade Obayomi", song: "Mad World", season: 7, style: "Contemporary", dancer_id: 20, url: nil, video_id: nil, partner_id: 2},
  {dancer_name: "Kent Boyd", partner: "Jose Ruiz", song: "From this Moment On", season: 7, style: "Broadway", dancer_id: 146, url: nil, video_id: nil, partner_id: 134},
  {dancer_name: "Lauren Froderman", partner: "AdéChiké Torbert ", song: "Fever", season: 7, style: "Foxtrot", dancer_id: 151, url: nil, video_id: nil, partner_id: 3},
  {dancer_name: "Billy Bell", partner: "Robert Roldan", song: "Ganesh", season: 7, style: "Bollywood", dancer_id: 20, url: nil, video_id: nil, partner_id: 194},
  {dancer_name: "Lauren Froderman", partner: "Pasha Kovalev", song: "Oblivion", season: 7, style: "Argentine Tango", dancer_id: 151, url: nil, video_id: nil, partner_id: 138},
  {dancer_name: "Kent Boyd", partner: "Courtney Galiano", song: "When Love Takes Over", season: 7, style: "Disco", dancer_id: 146, url: nil, video_id: nil, partner_id: 35},
  {dancer_name: "Lauren Froderman", partner: "Ade Obayomi", song: "Hide U", season: 7, style: "Jazz", dancer_id: 151, url: nil, video_id: nil, partner_id: 2},
  {dancer_name: "Kathryn McCormick", partner: "AdéChiké Torbert ", song: "Fearless Love", season: 7, style: "Contemporary", dancer_id: 143, url: nil, video_id: nil, partner_id: 3},
  {dancer_name: "Robert Roldan", partner: "Dominic Sandoval", song: "Scars", season: 7, style: "Hip-hop", dancer_id: 194, url: nil, video_id: nil, partner_id: 54},
  {dancer_name: "Kent Boyd", partner: "Neil Haskell", song: "How It Ends", season: 7, style: "Contemporary", dancer_id: 146, url: nil, video_id: nil, partner_id: 178},
  {dancer_name: "Twitch Boss", partner: "Lauren Froderman", song: "Power", season: 7, style: "Hip-hop", dancer_id: 206, url: nil, video_id: nil, partner_id: 151},
  {dancer_name: "Mark Kanemura", partner: "Robert Roldan", song: "Whip It", season: 7, style: "Jazz", dancer_id: 156, url: nil, video_id: nil, partner_id: 194},
  {dancer_name: "Lauren Froderman", partner: "Robert Roldan", song: "That Home", season: 7, style: "Contemporary", dancer_id: 151, url: nil, video_id: nil, partner_id: 194},
  {dancer_name: "Lauren Froderman", partner: "Kent Boyd", song: "Hip to be Square", season: 7, style: "Jazz", dancer_id: 151, url: nil, video_id: nil, partner_id: 146},
  {dancer_name: "Allison Holker", partner: "Kent Boyd", song: "Sundrenched World", season: 7, style: "Contemporary", dancer_id: 10, url: nil, video_id: nil, partner_id: 146},
  {dancer_name: "Kathryn McCormick", partner: "Robert Roldan", song: "Cool", season: 7, style: "Broy", dancer_id: 143, url: nil, video_id: nil, partner_id: 194},
  {dancer_name: "Lauren Froderman", partner: "Pasha Kovalev", song: "Not Myself Tonight", season: 7, style: "Cha-cha-cha", dancer_id: 151, url: nil, video_id: nil, partner_id: 138},
  {dancer_name: "Kent Boyd", partner: "Robert Roldan", song: "The Chosen/Drum Addict", season: 7, style: "Malevos", dancer_id: 146, url: nil, video_id: nil, partner_id: 194},
  {dancer_name: "Rayven Armijo", partner: "Jamie Bayard", song: "American Boy", season: 4, style: "Hip-Hop", dancer_id: 191, url: nil, video_id: nil, partner_id: 69},
  {dancer_name: "Susie Garcia", partner: "Marquis Cunningham", song: "Dark Waltz", season: 4, style: "Waltz", dancer_id: 198, url: nil, video_id: nil, partner_id: 158},
  {dancer_name: "Kourtni Lind", partner: "Matt Dorame", song: "Tainted Love", season: 4, style: "Jazz", dancer_id: 148, url: nil, video_id: nil, partner_id: 160},
  {dancer_name: "Chelsea Traille", partner: "Thayne Jasperson", song: "Oye Como Va", season: 4, style: "Cha-cha-cha", dancer_id: 38, url: nil, video_id: nil, partner_id: 200},
  {dancer_name: "Chelsie Hightower", partner: "Mark Kanemura", song: "Beautiful", season: 4, style: "Contemporary", dancer_id: 39, url: nil, video_id: nil, partner_id: 156},
  {dancer_name: "Kherington Payne", partner: "Twitch Boss", song: "Too Damn Hot", season: 4, style: "Broadway", dancer_id: 147, url: nil, video_id: nil, partner_id: 206},
  {dancer_name: "Katee Shean", partner: "Joshua Allen", song: "No Air", season: 4, style: "Lyrical hip-hop", dancer_id: 142, url: nil, video_id: nil, partner_id: 135},
  {dancer_name: "Jessica King", partner: "William Wingfield", song: "Tango", season: 4, style: "Tango", dancer_id: 128, url: nil, video_id: nil, partner_id: 211},
  {dancer_name: "Courtney Galiano", partner: "Gev Manoukian", song: "Boogie Wonderland", season: 4, style: "Disco", dancer_id: 45, url: nil, video_id: nil, partner_id: 62},
  {dancer_name: "Chelsea Traille", partner: "Thayne Jasperson", song: "Untouched", season: 4, style: "Jazz", dancer_id: 38, url: nil, video_id: nil, partner_id: 200},
  {dancer_name: "Chelsie Hightower", partner: "Mark Kanemura", song: "Mi Confesion", season: 4, style: "Argentine Tango", dancer_id: 39, url: nil, video_id: nil, partner_id: 156},
  {dancer_name: "Jessica King", partner: "William Wingfield", song: "Whatever U Like", season: 4, style: "Hip-Hop", dancer_id: 128, url: nil, video_id: nil, partner_id: 211},
  {dancer_name: "Courtney Galiano", partner: "Gev Manoukian", song: "Lost", season: 4, style: "Contemporary", dancer_id: 45, url: nil, video_id: nil, partner_id: 62},
  {dancer_name: "Katee Shean", partner: "Joshua Allen", song: "All for the Best", season: 4, style: "Broadway", dancer_id: 142, url: nil, video_id: nil, partner_id: 135},
  {dancer_name: "Susie Garcia", partner: "Marquis Cunningham", song: "Aguanile", season: 4, style: "Salsa", dancer_id: 198, url: nil, video_id: nil, partner_id: 158},
  {dancer_name: "Kherington Payne", partner: "Twitch Boss", song: "A New Day Has Come", season: 4, style: "Viennese Waltz", dancer_id: 147, url: nil, video_id: nil, partner_id: 206},
  {dancer_name: "Courtney Galiano", partner: "Gev Manoukian", song: "Wishing on a Star", season: 4, style: "Rumba", dancer_id: 45, url: nil, video_id: nil, partner_id: 62},
  {dancer_name: "Jessica King", partner: "William Wingfield", song: "Heaven Must Have Sent you", season: 4, style: "Disco", dancer_id: 128, url: nil, video_id: nil, partner_id: 211},
  {dancer_name: "Kourtni Lind", partner: "Matt Dorame", song: "Wrestlers", season: 4, style: "Contemporary", dancer_id: 148, url: nil, video_id: nil, partner_id: 160},
  {dancer_name: "Chelsea Traille", partner: "Thayne Jasperson", song: "You Can't Hurry Love", season: 4, style: "Quickstep", dancer_id: 38, url: nil, video_id: nil, partner_id: 200},
  {dancer_name: "Chelsie Hightower", partner: "Mark Kanemura", song: "Bleeding Love", season: 4, style: "Lyricalp-hop", dancer_id: 39, url: nil, video_id: nil, partner_id: 156},
  {dancer_name: "Katee Shean", partner: "Joshua Allen", song: "Baila, Baila", season: 4, style: "Samba", dancer_id: 142, url: nil, video_id: nil, partner_id: 135},
  {dancer_name: "Jessica King", partner: "William Wingfield", song: "Choo Choo Ch'Boogie", season: 4, style: "Jive", dancer_id: 128, url: nil, video_id: nil, partner_id: 211},
  {dancer_name: "Jessica King", partner: "William Wingfield", song: "Alone", season: 4, style: "Lyrical Jazz", dancer_id: 128, url: nil, video_id: nil, partner_id: 211},
  {dancer_name: "Comfort Fedoke", partner: "Thayne Jasperson", song: "Cool", season: 4, style: "Broadway", dancer_id: 44, url: nil, video_id: nil, partner_id: 200},
  {dancer_name: "Comfort Fedoke", partner: "Thayne Jasperson", song: "Hov Arek Sarer Jan", season: 4, style: "Smooth Waltz", dancer_id: 44, url: nil, video_id: nil, partner_id: 200},
  {dancer_name: "Kourtni Lind", partner: "Matt Dorame", song: "How Do I Breathe", season: 4, style: "Hip-hop", dancer_id: 148, url: nil, video_id: nil, partner_id: 160},
  {dancer_name: "Chelsie Hightower", partner: "Mark Kanemura", song: "Kiss Kiss", season: 4, style: "Jazz", dancer_id: 39, url: nil, video_id: nil, partner_id: 156},
  {dancer_name: "Chelsie Hightower", partner: "Mark Kanemura", song: "It's my Life", season: 4, style: "Foxtrot", dancer_id: 39, url: nil, video_id: nil, partner_id: 156},
  {dancer_name: "Kherington Payne", partner: "Twitch Boss", song: "Malaguena", season: 4, style: "Paso Doble", dancer_id: 147, url: nil, video_id: nil, partner_id: 206},
  {dancer_name: "Kherington Payne", partner: "Twitch Boss", song: "Dreaming with a Broken Heart", season: 4, style: "Contemporary", dancer_id: 147, url: nil, video_id: nil, partner_id: 206},
  {dancer_name: "Katee Shean", partner: "Joshua Allen", song: "Hometown Glory", season: 4, style: "Contemporary", dancer_id: 142, url: nil, video_id: nil, partner_id: 135},
  {dancer_name: "Courtney Galiano", partner: "Gev Manoukian", song: "Lights, Camera, Action!", season: 4, style: "Hip-hop", dancer_id: 45, url: nil, video_id: nil, partner_id: 62},
  {dancer_name: "Courtney Galiano", partner: "Gev Manoukian", song: "New York, New York", season: 4, style: "Broadway", dancer_id: 45, url: nil, video_id: nil, partner_id: 62},
  {dancer_name: "Chelsie Hightower", partner: "Mark Kanemura", song: "Fuego", season: 4, style: "Salsa", dancer_id: 39, url: nil, video_id: nil, partner_id: 156},
  {dancer_name: "Mark Kanemura", partner: "Chelsie Hightower", song: "I'm a Woman", season: 4, style: "Broadway", dancer_id: 156, url: nil, video_id: nil, partner_id: 39},
  {dancer_name: "Comfort Fedoke", partner: "Thayne Jasperson", song: "Can We Chill", season: 4, style: "Hip-hop", dancer_id: 44, url: nil, video_id: nil, partner_id: 200},
  {dancer_name: "William Wingfield", partner: "Jessica King", song: "Bandstand Boogie", season: 4, style: "Quickstep", dancer_id: 211, url: nil, video_id: nil, partner_id: 128},
  {dancer_name: "Courtney Galiano", partner: "Gev Manoukian", song: "Don't stop the Music", season: 4, style: "Cha-cha-cha", dancer_id: 45, url: nil, video_id: nil, partner_id: 62},
  {dancer_name: "Courtney Galiano", partner: "Gev Manoukian", song: "Standing There", season: 4, style: "Jazz", dancer_id: 45, url: nil, video_id: nil, partner_id: 62},
  {dancer_name: "Kherington Payne", partner: "Twitch Boss", song: "2 Buck 4 TV", season: 4, style: "Krump", dancer_id: 147, url: nil, video_id: nil, partner_id: 206},
  {dancer_name: "Kherington Payne", partner: "Twitch Boss", song: "Assassin's Tango", season: 4, style: "Tango", dancer_id: 147, url: nil, video_id: nil, partner_id: 206},
  {dancer_name: "Katee Shean", partner: "JosAllen", song: "Iris", season: 4, style: "Vienesse Waltz", dancer_id: 142, url: nil, video_id: nil, partner_id: 135},
  {dancer_name: "Katee Shean", partner: "Joshua Allen", song: "Dhoom Taana", season: 4, style: "Bollywood", dancer_id: 142, url: nil, video_id: nil, partner_id: 135},
  {dancer_name: "Courtney Gailiano", partner: "Joshua Allen", song: "Skippin", season: 4, style: "Hip-hop", dancer_id: 45, url: nil, video_id: nil, partner_id: 135},
  {dancer_name: "Courtney Gailiano", partner: "Joshua Allen", song: "Hero", season: 4, style: "Rumba", dancer_id: 45, url: nil, video_id: nil, partner_id: 135},
  {dancer_name: "Kherington Payne", partner: "Mark Kanemura", song: "Kick Back", season: 4, style: "Country-western two step", dancer_id: 147, url: nil, video_id: nil, partner_id: 156},
  {dancer_name: "Mark Kanemura", partner: "Kherington Payne", song: "Canned Heat", season: 4, style: "Jazz", dancer_id: 156, url: nil, video_id: nil, partner_id: 147},
  {dancer_name: "Twitch Boss", partner: "Comfort Fedoke", song: "Forever", season: 4, style: "Hip-hop", dancer_id: 206, url: nil, video_id: nil, partner_id: 44},
  {dancer_name: "Katee Shean", partner: "William Wingfield", song: "Sit Down You're Rocking the Boat", season: 4, style: "Broadway", dancer_id: 142, url: nil, video_id: nil, partner_id: 211},
  {dancer_name: "Katee Shean", partner: "William Wingfield", song: "Imagine", season: 4, style: "Pas de deux", dancer_id: 142, url: nil, video_id: nil, partner_id: 211},
  {dancer_name: "Chelsie Hightower", partner: "Gev Manoukian", song: "The House is Rockin", season: 4, style: "Jive", dancer_id: 39, url: nil, video_id: nil, partner_id: 62},
  {dancer_name: "Gev Manoukian", partner: "Chelsie Hightower", song: "These Arms of Mine", season: 4, style: "Contemporary", dancer_id: 62, url: nil, video_id: nil, partner_id: 39},
  {dancer_name: "Katee Shean", partner: "Twitch Boss", song: "Mercy", season: 4, style: "Contemporary", dancer_id: 142, url: nil, video_id: nil, partner_id: 206},
  {dancer_name: "Katee Shean", partner: "Twitch Boss", song: "Sweet Georgia Brown", season: 4, style: "Broadway", dancer_id: 142, url: nil, video_id: nil, partner_id: 206},
  {dancer_name: "Comfort Fedoke", partner: "Mark Kanemura", song: "Party People", season: 4, style: "Hip-hop", dancer_id: 44, url: nil, video_id: nil, partner_id: 156},
  {dancer_name: "Mark Kanemura", partner: "Comfort Fedoke", song: "Lady Luck", season: 4, style: "Foxtrot", dancer_id: 156, url: nil, video_id: nil, partner_id: 44},
  {dancer_name: "Joshua Allen", partner: "Chelsie Hightower", song: "A Los Amigos", season: 4, style: "Argentine Tango", dancer_id: 39, url: nil, video_id: nil, partner_id: 135},
  {dancer_name: "Chelsie Hightower", partner: "Joshua Allen", song: "Evsting Love", season: 4, style: "Disco", dancer_id: 39, url: nil, video_id: nil, partner_id: 135},
  {dancer_name: "Courtney Galiano", partner: "Mark Kanemura", song: "The Time of My Life", season: 4, style: "Viennese Waltz", dancer_id: 45, url: nil, video_id: nil, partner_id: 156},
  {dancer_name: "Courtney Galiano", partner: "Mark Kanemura", song: "The Garden", season: 4, style: "Jazz", dancer_id: 45, url: nil, video_id: nil, partner_id: 156},
  {dancer_name: "Katee Shean", partner: "Joshua Allen", song: "All By Myself", season: 4, style: "Contemporary", dancer_id: 142, url: nil, video_id: nil, partner_id: 135},
  {dancer_name: "Chelsie Hightower", partner: "Twitch Boss", song: "Ahora Me Toca a Mi", season: 4, style: "Mambo", dancer_id: 39, url: nil, video_id: nil, partner_id: 206},
  {dancer_name: "Twitch Boss", partner: "Chelsie Hightower", song: "Control", season: 4, style: "Hip-hop", dancer_id: 206, url: nil, video_id: nil, partner_id: 39},
  {dancer_name: "Katee Shean", partner: "Joshua Allen", song: "Slow Dancing in a Burning Room", season: 4, style: "Lyrical Jazz", dancer_id: 142, url: nil, video_id: nil, partner_id: 135},
  {dancer_name: "Courtney Galiano", partner: "Katee Shean", song: "The Trolley Song", season: 4, style: "Broadway", dancer_id: 45, url: nil, video_id: nil, partner_id: 142},
  {dancer_name: "Joshua Allen", partner: "Twitch Boss", song: "Trepak", season: 4, style: "Trepak", dancer_id: 135, url: nil, video_id: nil, partner_id: 206},
  {dancer_name: "Katee Shean", partner: "Twitch Boss", song: "Feeling Good", season: 4, style: "Foxtrot", dancer_id: 142, url: nil, video_id: nil, partner_id: 206},
  {dancer_name: "Courtney Galiano", partner: "Joshua Allen", song: "The Dirty Boogie", season: 4, style: "Jive", dancer_id: 45, url: nil, video_id: nil, partner_id: 135}
])
